Yoast/yoast-components

- composites/OnboardingWizard/Step.js
- composites/OnboardingWizard/components/StepComponents.js
- package.json
- Changed ConditionalTextInput to ConditionalInput
> Fixes to make the front-end work with the back-end

- App.js
- composites/OnboardingWizard/OnboardingWizard.js
- composites/OnboardingWizard/Step.js
- composites/OnboardingWizard/components/StepComponents.js
- composites/OnboardingWizard/config/production-config.js
Removed the customcomponents from the Stepcomponents file and added them default by `config.customComponents`.
I kept the custom components because they are used in the examples.
> Remove custom components

- composites/OnboardingWizard/OnboardingWizard.js
- composites/OnboardingWizard/Step.js
- composites/OnboardingWizard/helpers/ajaxHelper.js
- composites/OnboardingWizard/tests/wizardTest.js
- forms/Input.js
- forms/composites/Textfield.js
- Updated the postJSON helper to a more generic ajaxHelper.
- Added some checks needed for the MailChimpSignup custom component.
Testing:
1. Start the wizard.
2. Go through the steps and see if the data is correctly send. You can check this in the params in the response. The requests should be PUT requests.
> Add optimizations needed for the implementation of custom components

- forms/Input.js
- forms/tests/inputTest.js
The old value still returns when entering a new value.
Fixes #52
> Because of the old value came back.

- composites/OnboardingWizard/Step.js
Make sure each field gets the stepstate.
> Push the stepstate into the fields.

- CHANGELOG.MD
> Changelog 1.0

- css/_icons.scss
- forms/StyledSection/StyledSection.js
- forms/StyledSection/StyledSection.scss
- utils/i18n.js
These are prerequisites for the new insights section.
> Add StyledSection component and expose translate method

- composites/OnboardingWizard/helpers/ajaxHelper.js
- stubby/endpoints.yaml
Change the request type from PUT into POST, because not every webserver has PUT enabled.
> Change request type.

- style-guide/README.md
> Add basic guidelines to the readme file.

- package.json
Updates peer dependencies to work with: https://github.com/Yoast/wordpress-seo/pull/6149
Test instructions:
Make sure there is no unmet peer dependency when installing yoast components.
> Update package.json to meet peer dependencies

- a11y/tests/ScreenReaderShortcutTest.js
- a11y/tests/ScreenReaderTextTest.js
- composites/OnboardingWizard/tests/progressIndicatorTest.js
- composites/OnboardingWizard/tests/stepTest.js
- forms/StyledSection/StyledSection.scss
- forms/composites/tests/textfieldTest.js
- forms/tests/labelTest.js
- forms/tests/progressbarTest.js
This removes the fixed width from the section to make sure we can use `yoast-section` responsive.
> Removes width from section

- style-guide/_colors.scss
Added $palette_grey_light as $color_background.
> Added background color

- style-guide/_colors.scss
Removed duplicate background to revert out latest pull request, which was not necessary. The background color we added was already present in _colors.scss.
> Removed duplicate background

- composites/OnboardingWizard/OnboardingWizard.js
- composites/OnboardingWizard/config/production-config.js
This allows for better backward-compatibility
> Reverse navigation variable

- style-guide/_colors.scss
Add green medium color for the buttons on the new license page.
> Add green medium color

- README.md
- Add setup info
- Change `npm` to `yarn`
> Add setup info to README

- package.json
- yarn.lock
* Fix react-hot-loader entry in package.json.
* Added color_red_light
* fixed typo
* Add missing space
* Fix react-hot-loader entry in package.json.
* Upgrade jest-cli in .travis.yml
* Upgrade jest-cli in .travis.yml
* Print jest-cli and jest version in Travis
* fix
* fix
* Replaced yarn test -- --coverage by jest --coverage
* upgraded jest
* Revert .travis.yml
> Fix react-hot-loader entry in package.json. (#175)

- App.js
- composites/Plugin/ContentAnalysis/components/ContentAnalysis.js
Also I made it easier to add new components to App.js.
Fixes #231
> Added ContentAnalysis.js component in App.js

- composites/AlgoliaSearch/ArticleContent.js
- composites/AlgoliaSearch/tests/ArticleContentTest.js
- composites/AlgoliaSearch/tests/__snapshots__/ArticleContentTest.js.snap
- composites/basic/IFrame.js
- composites/basic/tests/IFrameTest.js
- composites/basic/tests/__snapshots__/IFrameTest.js.snap
Implement the IFrame component and the ArticleContent component. 
Fixes #212
> Add IFrame and ArticleContent

- composites/Plugin/ContentAnalysis/components/ContentAnalysis.js
- composites/Plugin/Shared/components/Button.js
- composites/Plugin/Shared/components/YoastButton.js
- composites/Plugin/Shared/tests/YoastButtonTest.js
- composites/Plugin/Shared/tests/__snapshots__/ButtonTest.js.snap
- composites/Plugin/Shared/tests/__snapshots__/YoastButtonTest.js.snap
* Adds a Button component with Yoast styles
First pass to add a Yoast-styled Button component.
The My Yoast buttons differ so much from the BaseButton that doesn't made sense to me to extend from there. I'd rather start from scratch.
- uses a `addButtonStyles()` function to add generic button styles meant to be used on both button and link elements, see #252 and #253 
- uses a `withTextShadow` to remove the button text shadow when necessary (with some color combinations the text shadow is necessary for a11y reasons, but with other combinations is just ugly and blurs the text)
- fixes a few typos in `Button.js`
Use the following code in `ContentAnalysis.js` (it includes all available buttons so far):
``` …
```
> Add Yoast button

- composites/Plugin/DashboardWidget/components/Divider.js
- composites/Plugin/DashboardWidget/components/SeoAssessment.js
- composites/Plugin/DashboardWidget/components/WordpressFeed.js
- composites/Plugin/DashboardWidget/tests/__snapshots__/WordpressFeedTest.js.snap
- composites/Plugin/Shared/components/ScoreAssessments.js
- composites/Plugin/Shared/components/StackedProgressBar.js
- composites/Plugin/Shared/tests/__snapshots__/ScoreAssessmentsTest.js.snap
- composites/Plugin/Shared/tests/__snapshots__/StackedProgresBarTest.js.snap
* Makes SeoAssessment and WordpressFeed styling consistent.
*
```js
import SeoAssessment from "../../DashboardWidget/components/SeoAssessment";
import WordpressFeed from "../../DashboardWidget/components/WordpressFeed";
import Divider from "../../DashboardWidget/components/Divider";
export const ContentAnalysisContainer = styled.div`
min-height: 700px;
`;
export const DashboardContainer = styled.div`
padding: 8px;
border: 1px solid black;
width: 400px;
`;
/**
* Returns the ContentAnalysis component.
*
* @returns {ReactElement} The ContentAnalysis component.
*/
export default function ContentAnalysis() {
const seoAssessmentItems = [
{ …
```
> Dashboard widget components styling improvements

- App.js
- app/DashboardWidgetWrapper.js
* Added dashboard widget to development environment
* Start development environment
* View the dashboard widget tab
> Added DashboardWidget to App.js

- composites/AlgoliaSearch/ArticleContent.js
- composites/AlgoliaSearch/tests/__snapshots__/ArticleContentTest.js.snap
Fixes https://github.com/Yoast/kb.yoast.com/issues/103
> Fix the URL to have a trailing /

- composites/Plugin/HelpCenter/HelpCenter.js
* Add a help center toggle callback function to use in the WP implementation
> Add help center toggle callback function

- composites/AlgoliaSearch/AlgoliaSearcher.js
Adds a prop to the algolia searcher to pass a callback function to retrieve the used search queries.
> Add callback for used queries

- CHANGELOG.MD
> Add changelog for 2.10

- CHANGELOG.MD
- composites/Plugin/HelpCenter/HelpCenter.js
- composites/Plugin/HelpCenter/tests/__snapshots__/HelpCenterTest.js.snap
- composites/Plugin/Shared/components/HelpCenterButton.js
- composites/Plugin/Shared/tests/__snapshots__/HelpCenterButtonTest.js.snap
Implement help center button tweaks.
Fixes #336
> Help center button tweaks

- composites/Plugin/ContentAnalysis/actions/contentAnalysis.js
- composites/Plugin/ContentAnalysis/actions/tests/ContentAnalysisTest.js
- composites/Plugin/ContentAnalysis/reducers/contentAnalysis/keywordResultsReducer.js
- composites/Plugin/ContentAnalysis/reducers/tests/keywordResultsReducerTest.js
* Adds setSeoResultsForKeyword action to seo analysis reducer
*
> Add setSeoResultsForKeyword action

- app/ContentAnalysisWrapper.js
- composites/Plugin/ContentAnalysis/components/ContentAnalysis.js
- composites/Plugin/ContentAnalysis/tests/ContentAnalysisTest.js
- composites/Plugin/ContentAnalysis/tests/__snapshots__/ContentAnalysisTest.js.snap
* NA
* I've added a prop `showLanguageNotice`
* Pass different values to `showLanguageNotice` and see what happens.
Fixes #361
> Language notice on readability tab

- app/ContentAnalysisWrapper.js
- composites/Plugin/ContentAnalysis/components/AnalysisResult.js
- composites/Plugin/ContentAnalysis/tests/AnalysisResultTest.js
- composites/Plugin/ContentAnalysis/tests/__snapshots__/AnalysisResultTest.js.snap
- composites/Plugin/ContentAnalysis/tests/__snapshots__/ContentAnalysisTest.js.snap
Add dangerouslySetInnerHTML to AnalysisResultText
* Look whether text with html tags is rendered correctly
> Add dangerouslySetInnerHTML to AnalysisResultText

- composites/Plugin/ContentAnalysis/components/ContentAnalysis.js
Adds a callback for the mark button on analysis results.
> Add ContentAnalysis mark button callback

- CHANGELOG.MD
> Add changelog for 2.11.2

- app/ContentAnalysisWrapper.js
- composites/Plugin/ContentAnalysis/components/ContentAnalysis.js
* 
*
* Check the console in the development environment, when marking and unmarking assessments.
* The following text will give you two markings:
```
Hallo. Hallo. Hallo.
He was helped.
```
Fixes #
> onMarkButtonClick callback returns empty id when button is unchecked

- CHANGELOG.MD
Make Onboarding Wizard Back and Next button focusable. #369
Replaced old react string refs with callbacks. #365
Added flag to run tests sequentially. #376
Dashboard widget progress bar height changed to 24px. #367
ContentAnalysis' onMarkButtonClick callback changed to return empty string when marker is deselected. #375
IconButtonToggle button received type="button" attribute. #378
> Updated changelog for 2.11.3

- CHANGELOG.MD
> Changelog part 2

- CHANGELOG.MD
> Updated changelog for 3.0

- App.js
- composites/Plugin/Shared/components/Checkbox.js
- composites/Plugin/Shared/tests/CheckboxTest.js
- composites/Plugin/Shared/tests/__snapshots__/CheckboxTest.js.snap
* Created a Checkbox React component, including a label.
* WordPress styling will overwrite styled.components, but we decided to cross that bridge when we get there.
* Checkout branch, **yarn start**, and navigate to http://localhost:3333/
* In Checkbox, there is the most generic form of a react checkbox and label.
* Clicking the label and the box should (un)check the box, and in the console it should log the value of the checkbox.
* In `App.js` you can toy around with the props that are passed to it.
Fixes #435
> Reactify checkbox

- a11y/examples/example.js
- composites/AlgoliaSearch/AlgoliaSearcher.js
- composites/AlgoliaSearch/ArticleContent.js
- composites/AlgoliaSearch/SearchResultDetail.js
- composites/Plugin/ContentAnalysis/components/AnalysisCollapsible.js
- composites/Plugin/Shared/components/Checkbox.js
- composites/Plugin/Shared/components/Collapsible.js
- composites/Plugin/Shared/components/SvgIcon.js
- composites/Plugin/Shared/components/YoastTabs.js
- composites/Plugin/SnippetPreview/components/InputField.js
- composites/Plugin/SnippetPreview/components/SnippetPreview.js
- composites/Plugin/SnippetPreview/components/SnippetPreviewExample.js
- composites/Plugin/SnippetPreview/components/fixedWidthContainer.js
- forms/Progressbar.js
- forms/Textarea.js
- package.json
- yarn.lock
* _Not applicable_
This means adding documentation to methods that didn't have
documentation yet.
> Update eslint-config-yoast to ^3.0

- .babelrc
- composites/AlgoliaSearch/tests/__snapshots__/AlgoliaSearcherTest.js.snap
- composites/AlgoliaSearch/tests/__snapshots__/SearchBarTest.js.snap
- composites/AlgoliaSearch/tests/__snapshots__/SearchResultDetailTest.js.snap
- composites/HelpCenter/views/tests/__snapshots__/VideoTutorialTest.js.snap
- composites/Plugin/ContentAnalysis/tests/__snapshots__/AnalysisCollapsibleTest.js.snap
- composites/Plugin/ContentAnalysis/tests/__snapshots__/ContentAnalysisTest.js.snap
- composites/Plugin/HelpCenter/tests/__snapshots__/HelpCenterTest.js.snap
- composites/Plugin/Shared/tests/__snapshots__/ButtonTest.js.snap
- composites/Plugin/Shared/tests/__snapshots__/CollapsibleTest.js.snap
- composites/Plugin/Shared/tests/__snapshots__/HelpCenterButtonTest.js.snap
- composites/Plugin/Shared/tests/__snapshots__/LinkButtonTest.js.snap
- composites/Plugin/Shared/tests/__snapshots__/YoastButtonTest.js.snap
- composites/Plugin/Shared/tests/__snapshots__/YoastLinkButtonTest.js.snap
- forms/StyledSection/tests/__snapshots__/styledSectionTest.js.snap
- package.json
- webpack.config.js
- yarn.lock
This makes the snapshots much easier to read.
* _Not applicable_
> Use babel styled components

- composites/AlgoliaSearch/AlgoliaSearcher.js
- composites/AlgoliaSearch/SearchResults.js
- package.json
- yarn.lock
* _Not applicable_
* I've run `yarn upgrade-interactive` until no packages needed to be updated.
> Updates all 'safe' dependencies

- composites/Plugin/HelpCenter/HelpCenter.js
> Change translation method for HelpCenter

- composites/basic/Notification.js
> Change translation method for Notification

- composites/Plugin/SnippetEditor/components/SnippetEditor.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
> Change translation method for SnippetEditor

- composites/Plugin/ContentAnalysis/components/ContentAnalysis.js
- composites/Plugin/ContentAnalysis/tests/__snapshots__/ContentAnalysisTest.js.snap
> Change translation method for ContentAnalysis

- composites/AlgoliaSearch/SearchBar.js
> Change translation method for SearchBar

- composites/AlgoliaSearch/SearchResults.js
> Change translation method for SearchResults

- composites/Plugin/SnippetEditor/constants.js
Reverts Yoast/yoast-components#523
> Revert "Quick fix warning custom_field replacevars"

- composites/Plugin/SnippetPreview/components/SnippetPreview.js
* N/A
* N/A
* N/A
Saw it during code review, and forgot to actually change it before merging.
> slug highlight comment

- app/SnippetEditorExample.js
- composites/Plugin/SnippetEditor/components/SnippetEditor.js
- composites/Plugin/SnippetEditor/components/SnippetEditorFields.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
- package.json
- yarn.lock
*
*
*
Fixes Yoast/YoastSEO.js#1496
> Change max meta description length

- README.md
* Fixes readme (Variable is referred to as though it were a string.
*
*
Fixes #
> Updates Bug in readme (refers to variable as string)

- a11y/ScreenReaderShortcut.js
- composites/AlgoliaSearch/SearchBar.js
- composites/AlgoliaSearch/SearchResultDetail.js
- composites/AlgoliaSearch/SearchResults.js
- composites/OnboardingWizard/OnboardingWizard.js
- composites/OnboardingWizard/Step.js
- composites/Plugin/DashboardWidget/tests/WordpressFeedTest.js
- composites/basic/Table/ListTable.js
- forms/Input.js
- forms/composites/Textfield.js
- grunt/config/eslint.js
* N/A
* Run `grunt eslint` and see that there is only one warning left.
* Introduce a warning and see `Warning: ESLint found too many warnings (maximum: 1) Use --force to continue.`
Fixes #
> Fix 11 eslint warnings and lower maxWarnings

- index.js
* Added collapsible as export of yoast-components
* See sibling pr: https://github.com/Yoast/wordpress-seo/pull/10456
Fixes #https://github.com/Yoast/wordpress-seo/issues/10304
> Added collapsible as export of yoast-components

- app/DashboardWidgetWrapper.js
- app/KeywordExample.js
Fixes the standalone app demo pages after recent changes.
- yarn start and go to localhost:3333 to check all the demo pages work without errors
> Fix the standalone app demo pages after recent changes

- composites/Plugin/SnippetEditor/components/SnippetEditor.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
* n/a
*
* Check if the string is outputted correctly and verify the next message is gone:
> Jed localization error:
> Error: Domain `yoast-components` was not found.
> Move translation of the placeholder to the constructor

- .eslintrc
- composites/OnboardingWizard/OnboardingWizard.js
- composites/OnboardingWizard/helpers/ajaxHelper.js
- composites/Plugin/Shared/components/Collapsible.js
- composites/Plugin/SnippetEditor/components/SnippetEditor.js
- composites/Plugin/SnippetEditor/serialization.js
- composites/Plugin/SnippetEditor/tests/ReplacementVariableEditorTest.js
- composites/Plugin/SnippetPreview/components/SnippetPreview.js
* _N/A_
* Renamed the variables that were already declared in a higher scope
* Make sure the functionality of the touched functions still works
* Snippet Preview title
* Snippet Preview mobile/desktop switcher
* Onboarding wizard steps
* Onboarding wizard AJAX requests (save/load data)
* Collapsible headings
Fixes #
> Resolve no-shadow eslint errors

- package.json
- yarn.lock
Reverts Yoast/yoast-components#769
> Revert "Bump YoastSEO.js to v. 1.41.1"
