Yoast/yoast-components

- composites/OnboardingWizard/Step.js
- composites/OnboardingWizard/config/production-config.js
- forms/composites/ConditionalTextField.js
To make the conditional text field work with the WP back-end the conditionalTextField is renamed to conditionalInput.
Testing:
1. Start the application
2. Go to step 4 and see if the radio buttons load.
3. Click the radio buttons and see if the conditional fields render.
> Change conditionalTextField to conditionalInput

- composites/OnboardingWizard/components/Choice.js
- composites/OnboardingWizard/config/production-config.js
- composites/OnboardingWizard/helpers/htmlDecoder.js
Separators are stored as html entities in the config. For this a HTML decoder is added. This translates the entities back to their symbols.
> Add html decoder for separator entities

- forms/composites/ConditionalTextField.js
- forms/composites/Textfield.js
The component crashed when leaving out not required values. To prevent this, default values are set for the optional props.
Also using a shape for the requires prop type in the ConditionalTextField made the application throw wrong warnings. Changed this to a required object instead of shape.
> Add default props for Textfield

- composites/OnboardingWizard/components/Choice.js
Just to associate the radiobutton with its label.
Fixes https://github.com/Yoast/wordpress-seo/issues/5533
> Use fieldname instead of choice value 

- package.json
This ensures that any implementation of `yoast-components` won't be missing particular dependencies that need to be installed by the party implementing one (or more) of our components.
> Added a missing peer dependency

- composites/OnboardingWizard/Step.js
- package.json
The input fields did not get unique keys in React. This caused some fields to get the value from another field when a step is re-rendered.
This also fixes the problem with the radio buttons from react 15.3.1, so the React version in the package is also set to 15.3.1.
Testing:
1. Start the wizard and go to step 4.
2. Fill in some text in the textfield.
3. Go to the next step and see if no input fields in that step have the value from the previous step.
Also test the radio buttons.
> Fix keys not unique for input components.

- composites/OnboardingWizard/OnboardingWizard.js
The label for the next button is renamed to ‘continue’ and on the last page to ‘close’. The close button redirects to the previous page.
Fixes https://github.com/Yoast/wordpress-seo/issues/5576
> Navigation buttons behaviour and text update.

- composites/OnboardingWizard/OnboardingWizard.js
- composites/OnboardingWizard/config/production-config.js
Use a finish url in the config. When pressing the close button in the wizard, this url is used to navigate to.
> Set finish url to go to when wizard has been finished

- composites/OnboardingWizard/StepButton.js
- composites/OnboardingWizard/StepIndicator.js
Fixes #77 
- adds an `aria-label` on the step buttons with a translatable string to announce, for example: `Step 4: Company or person`
- reset the `user-select: none` CSS property to `auto` on the inactive buttons tooltips since this causes a weird bug on Safari+VoiceOver, see https://github.com/Yoast/wordpress-seo/issues/5530
Screenshots using VoiceOver:
> Step buttons a11y improvements

- composites/OnboardingWizard/components/Choice.js
- forms/Label.js
The title separators are choice components. The special thing about this is that they contain a symbol and not text for a choice. The screen reader does not always give a good description for these symbols.
A solution for this is needed.
This PR can be summarized in the following change-log entry:
- Add more descriptive screen reader texts for choosing title separators.
Normally a label is sufficient for a screen reader, but now the labels contain symbols. The symbols are not always pronounced correctly. To override the default(visible) label content an aria-label is added. This replaces the symbol that the label contains with a more descriptive text for the screen reader. 
*
- Go to step 9 'title separators' in the wizard.
- Inspect the …
> Add screen reader text for choice component

- composites/OnboardingWizard/onboarding-wizard.scss
- composites/basic/YoastLogo.js
This PR removes incorrect SVG attributes/elements from the SVG image for the Yoast logo. They caused IE to crash when loading the wizard.
- Removed incorrect elements from SVG styling.
- Changed the id for the image to a class.
1. Start the wizard in Edge or IE
2. See if the wizard loads correctly and the logo is displayed correctly.
Fixes https://github.com/Yoast/wordpress-seo/issues/5641
Fixes https://github.com/Yoast/yoast-components/issues/65
> Update SVG logo to work with IE

- composites/OnboardingWizard/onboarding-wizard.scss
- Bigger max-width for text input fields.
This change is done based on this issue: https://github.com/Yoast/wordpress-seo/issues/5565
1. Start yoast-components from the release branch. 
2. Switch to the RW/bigger-textinput-width branch and build the css.
3. See if the text input is bigger.
4. Also switch to responsive mode and see if the input fields are shown correctly with smaller screens.
https://github.com/Yoast/wordpress-seo/issues/5565
> Set text input max-width to 450px

- composites/OnboardingWizard/onboarding-wizard.scss
Fixes #96 
Uses 
`.yoast-wizard-text-input [type="text"]`
instead of
`.yoast-wizard-text-input-field`
to target any text input field inside its container, regardless of the input CSS class.
> CSS selector to target all the input text fields.

- composites/OnboardingWizard/Step.js
- composites/OnboardingWizard/components/Choice.js
Added a small codestyle fix to https://github.com/Yoast/yoast-components/pull/123 and made this mergeable.
Fixes #114
This creates a choice component, that we could use for the multichoice component in issue #115 
For testing: 
- Use `yarn start` to start the webpack and open the onboarding wizard. 
- Make sure the radio buttons work as expected. 
- Add `"type": "select",` to a choice component. These should no longer be rendered as radiobuttons, but as selects.
> Adds Choice component

- composites/OnboardingWizard/StepIndicator.js
Simple enhancement for screen reader users. Will give context about the current step in the wizard:
Fixes https://github.com/Yoast/wordpress-seo/issues/7092
To test:
Run yarn start in the root folder.
Go to http://localhost:3333
click on "Wizard"
go through the steps and check `aria-current="step"` is on the active step button
> Add aria-current to the onboarding wizard active step.

- .babelrc
- webpack.config.js
Fixes a bug where the production build would fail when Yoast components is used as dependency in other projects (like `wordpress-seo`), because a dev dependency is used in the `.babelrc` file.
> Remove react-hot-loader/babel from .babelrc

- style-guide/_colors.scss
Fixes #184
All colors in _colors.scss should have an inline comment to give some indication about the other color they can be paired with to have a minimum color contrast ratio of 4.5:1
> Add inline comment for the new palette_red_light color

- README.md
Because of issues that arise when using `yarn link` as described in #161, I wrote up a small guide on how to develop `yoast-components` within `wordpress-seo`.
> Adds documentation on how to develop yoast-components within seo plugin

- package.json
- yarn.lock
Implemented `concurrently` package to provide a solid cross-platform way to start the development environment using `yarn start` or `npm start`.
Fixes #187
> Implemented concurrently to start the development environment

- composites/OnboardingWizard/helpers/ajaxHelper.js
On running `grunt check` ESLint would produce a warning about the complexity of the `parseRequestArgs` function. I reduced the complexity of this function by extracting a piece of functionality of this function to  `overwriteObjectWithDefaultValues` which does the exact same thing.
1. Make sure the development env is running.
2. Open te Configuration Wizard on `localhost:3333`.
3. Everytime you go to a different step in the wizard the newly added function is called.
4. Walk through the configuration wizard and make sure no unexpected behaviour occurs.
> Fixed ESLint ajaxHelper.js complexity warning

- composites/SnippetPreview/components/Icon.js
- composites/SnippetPreview/tests/IconTest.js
- composites/SnippetPreview/tests/__snapshots__/IconTest.js.snap
- jest/__mocks__/fileMock.js
- jest/__mocks__/svgReactLoaderMock.js
- package.json
- style-guide/svg/edit.svg
- style-guide/svg/index.js
- webpack.config.js
- yarn.lock
Also added jest configuration to map svg files to `/jest/__mocks__/svgReactLoaderMock.js`, because jest doesn't use webpack loaders.
* Implemented `svg-react-loader`, which creates react components from `.svg` files.
* Added svg mocking instructions to `package.json` that tell jest to mock imports of `.svg` files to `/jest/__mocks__/svgReactLoaderMock.js`.
1. Paste the following in `SnippetPreview.js`:
```js
import { Icon } from "./Icon";
import { edit } from "../../../style-guide/svg";
export const SnippetPreviewDiv = styled.div`
height: 700px;
width: 100%;
`;
/**
* Returns the SnippetPreview component.
*
* @returns {ReactElement} The SnippetPreview component.
*/
export default function …
```
> Added Svg Icon component using svg-react-loader

- composites/SnippetPreview/components/Icon.js
- composites/SnippetPreview/tests/IconTest.js
- package.json
When applying a `styled-components` decorator to apply some additional stying to the Icon component I found out the changes were not showing up.
This PR fixes that by passing all props that are not specific for the Icon down to the outputted component. By using `lodash`'s `omit` all props that are not specific to the Icon component are removed and passed to the returned component.
This also allows the Icon's API to be cleaner by changing `iconSize` and `iconColor` to `size` and `color` respectively, because they won't be passed down to the html element as attributes anyway.
To test replace the content of `SnippedPreview.js` with the following content:
```js
import { Icon } from "./Icon";
import { edit } from …
```
> Allow non-Icon specific props to be passed down in Icon component

- README.md
Added documentation about which middlewares and reducers should be used when using the Content analysis component.
Fixed #237
> Documentation about reducers and middleware

- composites/OnboardingWizard/Step.js
- composites/OnboardingWizard/onboarding-wizard.scss
Applied the max-width of 560 px to the onboarding wizard width. Reduced the size of the seperator tiles slightly to have them fit on a single line.
Testinstructions:
1. Make sure you run grunt build
2. Checkout the wizard on localhost:3333. Take a quick look at each page of the wizard to make sure the pages look presentable, and pay particular atttention to the width of the content of the pages, confirming they don't exceed the 560 pixels set in the issue.
fixes #245
> Applied a max width to the onboarding wizard content

- composites/OnboardingWizard/components/Choice.js
- composites/OnboardingWizard/onboarding-wizard.scss
Fixes #244
Related #240
Added a property to the choice component, which can be used to send a paragraph of text, which should be displayed between the title of the choice and the radio buttons. 
I gave the component the name `description` instead of `html`.
Test instructions:
to the choice-component where you want to add a description (let's say the company website/personal website of page 4 of the wizard), add "descriptions" to the properties of "properties". I've added it to the example page in the code block below, simply replace the entire "publishingEntity" around line 86 of production-config.js.
```
"publishingEntity": {
"componentName": "Choice",
"properties": {
"label": "Is this a personal site or is it for a company?",
"choices": {
"person": {
"label": "Personal website",
}, …
```
> 244 choice component subtext

- composites/OnboardingWizard/OnboardingWizard.js
- composites/OnboardingWizard/StepIndicator.js
* Added landmark regions for assistive technologies to the Configuration wizard.
* will be completed by #256  and https://github.com/Yoast/wordpress-seo/issues/7807
* use a screen reader and check the landmark regions are reported correctly, for example with Safari+VoiceOver 
* press Control-Option-U to open the Rotor
* press Control-Option-Right arrow (or Left) to reach the Landmark list
* verify the navigation and main regions are listed
* press Control-Option-Down arrow (or Up) to select one of the regions and jump to it
Fixes #258
> Add nav and main landmarks to the Configuration wizard

- composites/SnippetPreview/components/SnippetPreview.js
* 
* Temporarily added a `SnippetPreview.js` in its previous location (before folder restructure introduced in PR #232), to ensure backwards compatibility.
* Import SnippetPreview from its previous location `composites/SnippetPreview/components/SnippetPreview.js`, and make sure it's the same component as `composites/Plugin/SnippetPreview/components/SnippetPreview.js`.
> Added backwards compatibility for SnippetPreview.js

- composites/Plugin/Shared/components/Button.js
- composites/Plugin/Shared/components/LinkButton.js
- composites/Plugin/Shared/tests/LinkButtonTest.js
- composites/Plugin/Shared/tests/__snapshots__/ButtonTest.js.snap
- composites/Plugin/Shared/tests/__snapshots__/LinkButtonTest.js.snap
* Added LinkButton component.
Noticed a pre-existing CSS issue in the buttons, where `min-height` triggers a bug in IE 11 and other CSS produced misplaced icon and text in Edge. I think we're maybe a bit too much optimistic with `flexbox`, it doesn't work so well in some browsers especially with SVG icons (not just old browsers but also Safari...)
Details on the IE bug:
https://github.com/philipwalton/flexbugs#3-min-height-on-a-flex-container-wont-apply-to-its-flex-items
min-height on a flex container won't apply to its flex items - Internet Explorer 10-11 (fixed in Edge)
IE 11:
Edge:
Easiest fix for the IE 11 bug: use height instead. Was there a specific reason to use min-height?
The CSS changes introduced here are not perfect, …
> 252 linkbutton component

- composites/OnboardingWizard/config/api-config.js
- webpack.config.js
* Test environment can be served to machines in the same network ( i.e. mobile phones )
* Host has been changed from `localhost` to `0.0.0.0`.
* Make sure your firewall/router settings allow you to connect to the machine that is serving the test environment.
* Run the test environment (`yarn start`).
* Open a browser on a different device in your network and open `[your device's ip]:3333`
> Added configuration to allow test environment to be served to network.

- package.json
- yarn.lock
I've added the `striptags` library. A lightweight, tested and well-maintained library with almost 200 stars [on github](https://github.com/ericnorris/striptags).
* Added a utility library for stripping html tags.
* Added lightweight `striptags` library.
* `yarn install`
* Test the library by importing it into a file, and test some strings containing HTML tags with it.
Fixes #275
> Added striptags library for removing HTML tags

- composites/Plugin/Shared/components/Icon.js
- composites/Plugin/Shared/tests/__snapshots__/ButtonTest.js.snap
- composites/Plugin/Shared/tests/__snapshots__/IconTest.js.snap
- style-guide/svg/edit.svg
* Improved SVG icons accessibility
* adds the following attributes to the SVG markup: `role="img" aria-hidden="true" focusable="false"`
* `role="img" aria-hidden="true"` make sure the icon is exposed to assistive technologies like an image and **not** announced
* `focusable="false"` fixes an IE 11 bug: when SVG icons are within focusable elements, they're considered focusable too, thus requiring to press Tab twice to navigate
* to test the IE 11 bug, use the following code in ContentAnalysis.js and verify you have to press Tab just once
```
import { IconButton } from "../../Shared/components/Button";
import { edit } …
```
> SVG edit icon improvements

- composites/OnboardingWizard/LoadingIndicator.js
* Fixes a console error when switching pages in the Onboarding wizard.
1. Open the OnboardingWizard and go to the next step.
2. Verify that the prop warning is no longer showing up in the console.
1. Place `debugger;` as the first line in the `handleSuccessful` function in `OnboardingWizard.js`.
2. Open the OnboardingWizard and make sure you have the chrome debug tools open.
3. Go to the next step. Wait for the code execution to be paused by the `debugger` statement.
4. Search for the div where the loading indicator is rendered. It's **inside** a div with the class `"yoast-wizard-overlay-loader"`. Verify that the styles have been applied to this div.
```css
justify-content: …
```
> Fix justify-content & z-index prop warning on LoadingIndicator component

- composites/Plugin/Shared/components/Button.js
- composites/Plugin/Shared/components/YoastButton.js
- composites/Plugin/Shared/components/YoastLinkButton.js
- composites/Plugin/Shared/tests/YoastLinkButtonTest.js
- composites/Plugin/Shared/tests/__snapshots__/ButtonTest.js.snap
- composites/Plugin/Shared/tests/__snapshots__/LinkButtonTest.js.snap
- composites/Plugin/Shared/tests/__snapshots__/YoastButtonTest.js.snap
- composites/Plugin/Shared/tests/__snapshots__/YoastLinkButtonTest.js.snap
* Add Yoast Link Button component.
* switches everything to `display: inline-flex;`
* adds a `YoastButtonBase` component that is a button with an inner span element to fix a Safari 10 bug, see https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers
This turned out to be a bit more complicated than expected. Safari 10 doesn't apply correctly flexbox on `<button>` elements. The suggested fix is to add an inner `<span>` and give it the necessary flex properties. I'm styling it inheriting some CSS properties from the parent button. Worth noting this bug seems fixed in Safari Technology Preview so in the future it will be possible to remove the fix: remove `YoastButtonBase` and directly style a button …
> Add Yoast Link Button component.

- composites/Plugin/Shared/components/A11yNotice.js
- composites/Plugin/Shared/tests/A11yNoticeTest.js
- composites/Plugin/Shared/tests/__snapshots__/A11yNoticeTest.js.snap
* Adds an invisible A11y component for screen readers.
* Made the component a `span` element by default, but this can be overwritten with `styled-components`'s [`.withComponent`](https://www.styled-components.com/docs/api#withcomponent) function.
* Copy the following content into `ContentAnalysis.js`:
```js
import { A11yNotice } from "../../Shared/components/A11yNotice";
export const ContentAnalysisContainer = styled.div`
min-height: 700px;
width: 100%;
`;
/**
* Returns the ContentAnalysis component.
*
* @returns {ReactElement} The ContentAnalysis component.
*/
export default function …
```
> Implement A11yNotice component

- composites/Plugin/Shared/components/YoastTabs.js
- composites/Plugin/Shared/tests/YoastTabsTest.js
- composites/Plugin/Shared/tests/__snapshots__/YoastTabsTest.js.snap
- package.json
- yarn.lock
* Adds the Help Center ARIA tabs widget component
* Introduces `react-tabs`
* use the following code in ContentAnalysis
```
import YoastTabs from "../../Shared/components/YoastTabs";
export const ContentAnalysisContainer = styled.div`
min-height: 700px;
padding: 40px;
`;
let items = [
{
id: "tab1",
label: "video tutorial",
content: <p>This is some content for tab 1. <a href="#">focusable element 1</a></p>,
},
{
id: "tab2",
label: "knowledge base",
content: <p>This is some content for tab 2. <a href="#">focusable element 2</a></p>,
},
{
id: "tab3",
label: "email support",
content: <p>This is …
```
> Introduce react-tabs for the Help Center tabs.

- composites/OnboardingWizard/StepIndicator.js
Fun fact: I have no idea how this fixes the error.
* Fixes react prop types console error in Onboarding Wizard.
* Open the onboarding wizard
* Notice that the error is no longer there
Fixes #180
> Fixed StepButton prop types error

- composites/AlgoliaSearch/ArticleContent.js
- composites/Plugin/ContentAnalysis/components/ContentAnalysis.js
- composites/Plugin/Shared/components/YoastTabs.js
- composites/Plugin/Shared/tests/__snapshots__/YoastTabsTest.js.snap
* Reset the outline style on the react tab panels
* test with this code in ContentAnalysis, then tab from the tabs to the tabpanels and check they don't display the outline style when focused
```
import YoastTabs from "../../Shared/components/YoastTabs";
export const ContentAnalysisContainer = styled.div`
min-height: 700px;
padding: 40px;
`;
let items = [
{
id: "tab1",
label: "video tutorial",
content: <p>This is some content for tab 1. <a href="#">focusable element 1</a></p>,
},
{
id: "tab2",
label: "knowledge base",
content: <p>This is some content for tab 2. <a href="#">focusable element …
```
> Reset outline style on the react tab panels.

- App.js
- index.html
- index.js
* Add HelpCenter to index.js
* Add HelpCenter to index.js
* Remove unused props from HelpCenterWrapper implementation
* Change title in the index.html to 'Yoast Components'
Last part of the implementation of #203 
Fixes #203
> Add Help Center to index

- composites/AlgoliaSearch/tests/__snapshots__/AlgoliaSearcherTest.js.snap
- composites/AlgoliaSearch/tests/__snapshots__/SearchBarTest.js.snap
- composites/AlgoliaSearch/tests/__snapshots__/SearchResultDetailTest.js.snap
- composites/Plugin/HelpCenter/tests/__snapshots__/HelpCenterTest.js.snap
- composites/Plugin/Shared/components/YoastButton.js
- composites/Plugin/Shared/tests/__snapshots__/HelpCenterButtonTest.js.snap
- composites/Plugin/Shared/tests/__snapshots__/YoastButtonTest.js.snap
- composites/Plugin/Shared/tests/__snapshots__/YoastLinkButtonTest.js.snap
* Improved Yoast Button hover/focus/active style.
* explicitly sets the `color` property on the Yoast Buttons for hover/focus/style so it's inherited also by the Yoast Link Buttons and avoids inheritance from the WP rules 
* Test in the WP integration, the Algolia search "View in KB" link button on hover and focus: color should stay white
Fixes #326
> Improve yoast button link hover style

- app/HelpCenterWrapper.js
- composites/AlgoliaSearch/AlgoliaSearcher.js
- composites/AlgoliaSearch/SearchBar.js
- composites/AlgoliaSearch/SearchResultDetail.js
- composites/AlgoliaSearch/tests/__snapshots__/AlgoliaSearcherTest.js.snap
- composites/AlgoliaSearch/tests/__snapshots__/SearchBarTest.js.snap
- composites/AlgoliaSearch/tests/__snapshots__/SearchResultDetailTest.js.snap
- composites/HelpCenter/views/VideoTutorial.js
- composites/HelpCenter/views/tests/__snapshots__/VideoTutorialTest.js.snap
* Better match the design specs
- AlgoliaSearcher: make the prop maxWidth not required and set it to 900px
- SearchBar: make the search field (and label, the lens icon) height 48px so it doesn't depend on the inherited font-size
- SearchResultDetail: improve a bit the top buttons position
- VideoTutorial: set max-width 900px
> AlgoliaSearcher and VideoTutorial CSS adjustments.

- composites/AlgoliaSearch/AlgoliaSearcher.js
- composites/AlgoliaSearch/SearchBar.js
- composites/AlgoliaSearch/tests/__snapshots__/AlgoliaSearcherTest.js.snap
- composites/AlgoliaSearch/tests/__snapshots__/SearchBarTest.js.snap
- composites/HelpCenter/views/VideoTutorial.js
- composites/HelpCenter/views/tests/__snapshots__/VideoTutorialTest.js.snap
* Adjusted Help Center styling for integration in WordPress.
- need to increase the specificity of some CSS selectors to avoid conflicts with rules inherited from WordPress. However, styled components don't allow to increase specificity easily other than:
- using `!important`
- using `&&` to double the generated class selector, see https://github.com/Yoast/yoast-components/issues/343#issuecomment-334737666 
- removes the maxWidth prop form the components used in the Yoast tabs
* Please see testing instructions on the related Plugin's PR
Fixes #329
> Help center css tweaks

- composites/AlgoliaSearch/AlgoliaSearcher.js
- composites/AlgoliaSearch/SearchResultDetail.js
- composites/AlgoliaSearch/SearchResults.js
- composites/AlgoliaSearch/tests/__snapshots__/SearchResultDetailTest.js.snap
- composites/AlgoliaSearch/tests/__snapshots__/SearchResultsTest.js.snap
* Improved keyboard focus accessibility in the Knowledge Base search results.
Please refer to the issue for the description of a few technical difficulties to face here. Had to use DOM methods, not particularly happy for that, but couldn't find a better way. Happy to rework this if anyone has better ideas.
* using the keyboard to navigate, verify focus is not lost
* when going from the search results to a search details focus should go on the detail wrapper
* when going back, focus should go on the result link that was previously clicked
* use a screen reader to check the aria-label on the detail wrapper
Fixes #338
> Improve search results and detail focus management.

- composites/HelpCenter/views/VideoTutorial.js
- composites/HelpCenter/views/tests/__snapshots__/VideoTutorialTest.js.snap
* Adds classes to the video-tutorial elements.
* Added classes to the specific elements of the video tutorial to allow overriding behaviour on specific implementations.
Testing:
Verify the snapshots contain the class names.
Related https://github.com/Yoast/wordpress-seo/issues/8039
> Add classes to provide the ability to override styles

- composites/Plugin/ContentAnalysis/reducers/tests/keywordResultsReducerTest.js
Adds an extra test for keywordResultsReducer to test if it overwrites seo results for a single keyword when there are already results for that keyword.
* Run `yarn test`.
>  Add extra test for keywordResultsReducer

- composites/HelpCenter/views/VideoTutorial.js
* Add default classname `yoast-video-tutorial` to the VideoDescriptionItem.
* Set the same default classname as in the video tutorial component.
* Run yarn test and check whether the warning is gone.
Fixes #357
> Set default classname

- App.js
- app/ContentAnalysisWrapper.js
- composites/Plugin/ContentAnalysis/components/AnalysisCollapsible.js
- composites/Plugin/ContentAnalysis/components/AnalysisResult.js
- composites/Plugin/ContentAnalysis/components/ContentAnalysis.js
- composites/Plugin/ContentAnalysis/tests/AnalysisCollapsibleTest.js
- composites/Plugin/ContentAnalysis/tests/ContentAnalysisTest.js
- composites/Plugin/ContentAnalysis/tests/__snapshots__/AnalysisCollapsibleTest.js.snap
- composites/Plugin/ContentAnalysis/tests/__snapshots__/AnalysisResultTest.js.snap
- composites/Plugin/ContentAnalysis/tests/__snapshots__/ContentAnalysisTest.js.snap
* Added Content Analysis Component.
* I've decided to make the analysis result categories (errors, improvements etc.) static, although they are not shown when there is no result in that specific category. For now, I don't see any reason to pass categories as a prop, and implementing it that way would make this component way more complex. 
* The bullet is merely decorative. All information needed is communicated through the headings. 
* Discussed header order with @hedgefield: errors, problems, improvements, considerations, good. The collapsibles of errors and problems should be opened by default, the other categories don't.
* The language notice should only be shown in the readability analysis (not in the SEO analysis). What …
> Implement content analysis component

- composites/Plugin/ContentAnalysis/components/ContentAnalysis.js
- composites/Plugin/ContentAnalysis/tests/__snapshots__/ContentAnalysisTest.js.snap
* Remove `min-height` from Content Analysis component.
* Look at the ContentAnalysis component in the app.js
Fixes #371
> Remove minheight from Content Analysis component.

- composites/Plugin/Shared/components/StackedProgressBar.js
- composites/Plugin/Shared/tests/__snapshots__/StackedProgressBarTest.js.snap
* Changes the dashboard widget progress bar height from 40px to 24 px.
Fixes https://github.com/Yoast/wordpress-seo/issues/8123
> Change dashboard widget progress bar height

- .travis.yml
Speeds up Travis by running Jest sequentially
Before: 
43.00s
48.21s
After:
17.27s
20.74s
> Speed up Travis by running Jest sequentially

- composites/OnboardingWizard/OnboardingWizard.js
- composites/OnboardingWizard/Step.js
- composites/Plugin/SnippetPreview/components/InputField.js
- composites/SearchResultForm/SearchResultForm.js
- composites/SearchResultPreview/SearchResultPreview.js
* Removes the deprecated `refs` and replaces them with ref callbacks.
* Test the onboarding wizard and algolia searcher and make sure no errors occur.
Fixes #351
> Replaced all string refs to ref callbacks

- composites/OnboardingWizard/OnboardingWizard.js
* Made the Onboarding Wizard previous and next buttons focusable again
* Removes the `disableKeyboardFocus` from the buttons. Seems this prop was initially used in material-ui just for styling purposes, instead now it's also responsible for setting the tabindex attribute.
- on the develop branch, use the keyboard to Tab to the buttons and see they're not focusable
- see they have a `tabindex="-1"` attribute
- switch to this branch
- check the buttons are now focusable
- check they have a `tabindex="0"` attribute
Aside note: as mentioned in the issue, `material-ui` does lots of things to control elements focusability programmatically. Not sure I really like this approach. Keeping controls behaviors as native as possible is always …
> Make the Wizard previous and next buttons focusable again

- composites/Plugin/ContentAnalysis/tests/__snapshots__/AnalysisResultTest.js.snap
- composites/Plugin/ContentAnalysis/tests/__snapshots__/ContentAnalysisTest.js.snap
- composites/Plugin/Shared/components/IconButtonToggle.js
- composites/Plugin/Shared/tests/__snapshots__/IconButtonToggleTest.js.snap
* Fixes error in wordpress-seo causing random refresh on content analysis marker button
*
* Checkout `feature/reactify-content-analysis` in `wordpress-seo`
* Change `yoast-components` version to this branch `https://github.com/Yoast/yoast-components.git#stories/icon-button-toggle-type-button`
* Run `grunt build:js`
* Open the classic editor and paste the following text into the visual editor: `Here is some text. Here is some more. Here is a unicorn.`. Switch to the readability analysis and inspect the button next to the `The text contains 3 consecutive sentences starting with the same word. Try to mix things up!` result. Make sure it has the `type="button"` attribute.
* Click the …
> Make IconButtonToggle type button

- composites/Plugin/ContentAnalysis/components/AnalysisCollapsible.js
- composites/Plugin/ContentAnalysis/components/AnalysisResult.js
- composites/Plugin/ContentAnalysis/tests/__snapshots__/AnalysisCollapsibleTest.js.snap
- composites/Plugin/ContentAnalysis/tests/__snapshots__/AnalysisResultTest.js.snap
- composites/Plugin/ContentAnalysis/tests/__snapshots__/ContentAnalysisTest.js.snap
* Remove unnecessary whitespace between `AnalysisResult`s and between `AnalysisCollapsible`s
Old situation:
New situation:
Old situation:
New situation:
* Compare whitespace between `develop` and this branch using localhost:3333. Please note that WP adds extra whitespace. 
Fixes #381
> Content analysis css tweaks

- composites/Plugin/ContentAnalysis/components/ContentAnalysis.js
- composites/Plugin/ContentAnalysis/tests/ContentAnalysisTest.js
- composites/Plugin/ContentAnalysis/tests/__snapshots__/ContentAnalysisTest.js.snap
* Made it possible to pass the heading level of the `analysisCollapsible`s as a prop to the `ContentAnalysis` #388.
* I've set the default to H4 because that's the level we want in Wordpress SEO (as discussed with @afercia)
* Play around with passing heading levels to the standalone ContentAnalysis component.
* For testing in wordpress-seo: Replace the yoast-components version in the package.json by `"git+https://github.com/Yoast/yoast-components#stories/8310-content-analysis-heading-structure"`. Don't forget to run `yarn install` and `grunt build`. Also, do a **hard reset with cache clearing** before inspecting. The heading level in the plugin should be H4 (the default).
Fixes #387
> Pass heading level as a prop to the content analysis

- composites/Plugin/ContentAnalysis/components/AnalysisCollapsible.js
* Avoid to fully re-render the collapsible header to improve accessibility
* moved the evaluation of the "wrapping" to avoid to run `wrapInHeading()` in the stateless component, which is rendered every time a button gets clicked
- before switching to this branch, go in the Content Analysis tab
- using Safari and VoiceOver, focus one ot the results heading
- using Control-Option-Spacebar, activate the button in the heading
- do it on different headings, multiple times
- observe how the `aria-expanded` change is not announced correctly and there's a focus loss, sometimes it's very evident focus goes on a different element
- switch to this branch
- repeat the steps above
- observe …
> Avoid collapsible header button full re-render.

- composites/Plugin/ContentAnalysis/components/ContentAnalysis.js
- composites/Plugin/ContentAnalysis/tests/__snapshots__/ContentAnalysisTest.js.snap
* Expands all `AnalysisCollapsibles` in the `ContentAnalysis` by default.
* Link this branch to wordpress-seo (5.9 branch).
* Open a post. All analysis headings should be expanded by default.
Fixes #392
> Expand all headings in content analysis by default

- app/ContentAnalysisWrapper.js
- composites/Plugin/ContentAnalysis/components/AnalysisResult.js
- composites/Plugin/ContentAnalysis/components/ContentAnalysis.js
- composites/Plugin/ContentAnalysis/tests/AnalysisResultTest.js
- composites/Plugin/ContentAnalysis/tests/ContentAnalysisTest.js
- composites/Plugin/ContentAnalysis/tests/__snapshots__/AnalysisResultTest.js.snap
- composites/Plugin/ContentAnalysis/tests/__snapshots__/ContentAnalysisTest.js.snap
- composites/Plugin/Shared/components/IconButtonToggle.js
- composites/Plugin/Shared/tests/IconButtonToggleTest.js
- composites/Plugin/Shared/tests/__snapshots__/IconButtonToggleTest.js.snap
- renovate.json
* Added a prop to the `ContentAnalysis` to disable or hide the eye buttons.
* I've reset the cursor to `default` rather than `pointer` on hovering a disabled button. This is consistent with what WP is doing. 
* I've changed the icon color of the disabled button to #ddd ($color_grey) instead of #e6e6e6 (which is not in the colors.json). #ddd is a little darker, but the background is darker as well,
because now there is a button background instead of the white meta box background. The color contrast is 1.27 instead of 1.25 🎉 .
* The design of the disabled button has been approved by @hedgefield.
* Check out this branch.
* `yarn install`,`yarn start`
* Go to `localhost:3333`
* Change …
> Add prop to disable and hide marking buttons

- composites/AlgoliaSearch/SearchBar.js
- composites/AlgoliaSearch/tests/__snapshots__/AlgoliaSearcherTest.js.snap
- composites/AlgoliaSearch/tests/__snapshots__/SearchBarTest.js.snap
* Updated Knowledge Base search input field and labels.
Worth noting I'm updating the value of the `autocapitalize` attribute, since `off` is deprecated and `none` is the one to use today: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
* for the standalone version, just `yarn start` and go on http://localhost:3333/
* for the plugin, yarn link or use this branch in your package.json, switch the plugin to the `stories/410-kb-search-bar-tweaks` branch see https://github.com/Yoast/wordpress-seo/pull/8484 and build the JS
Screenshots:
Fixes #410
> Tweak kb search input field.

- composites/Plugin/ContentAnalysis/components/ContentAnalysis.js
- composites/Plugin/ContentAnalysis/tests/__snapshots__/ContentAnalysisTest.js.snap
Updates the default message for the "Good" assessments heading.
**Make sure this PR is released and updated in wordpress-seo before the 6.3 RC.**
Fixes https://github.com/Yoast/wordpress-seo/issues/8532
> Update good results heading default message.

- composites/AlgoliaSearch/tests/__snapshots__/SearchResultDetailTest.js.snap
- composites/Plugin/ContentAnalysis/tests/__snapshots__/AnalysisCollapsibleTest.js.snap
- composites/Plugin/ContentAnalysis/tests/__snapshots__/AnalysisResultTest.js.snap
- composites/Plugin/ContentAnalysis/tests/__snapshots__/ContentAnalysisTest.js.snap
- composites/Plugin/HelpCenter/tests/__snapshots__/HelpCenterTest.js.snap
- composites/Plugin/Shared/components/SvgIcon.js
- composites/Plugin/Shared/tests/__snapshots__/ButtonTest.js.snap
- composites/Plugin/Shared/tests/__snapshots__/HelpCenterButtonTest.js.snap
- composites/Plugin/Shared/tests/__snapshots__/IconButtonToggleTest.js.snap
- composites/Plugin/Shared/tests/__snapshots__/SvgIconTest.js.snap
- composites/basic/tests/__snapshots__/NotificationTest.js.snap
- forms/StyledSection/tests/__snapshots__/styledSectionTest.js.snap
* Adds css styles to `SvgIcon` component to fix irregular sizing in `wordpress-seo`.
* 
Fixes #425
> Fix svg icon size

- composites/Plugin/ContentAnalysis/tests/__snapshots__/AnalysisCollapsibleTest.js.snap
- composites/Plugin/ContentAnalysis/tests/__snapshots__/ContentAnalysisTest.js.snap
- composites/Plugin/HelpCenter/tests/__snapshots__/HelpCenterTest.js.snap
- composites/Plugin/Shared/components/SvgIcon.js
- composites/Plugin/Shared/tests/__snapshots__/ButtonTest.js.snap
- composites/Plugin/Shared/tests/__snapshots__/HelpCenterButtonTest.js.snap
* Changed `SvgIcon`'s default prop `size` from `16` to `16px` and correctly implemented default props.
> Fix default props in svg icon component

- composites/Plugin/ContentAnalysis/components/AnalysisCollapsible.js
- composites/Plugin/ContentAnalysis/components/ContentAnalysis.js
- composites/Plugin/ContentAnalysis/tests/AnalysisCollapsibleTest.js
- composites/Plugin/ContentAnalysis/tests/__snapshots__/AnalysisCollapsibleTest.js.snap
- composites/Plugin/ContentAnalysis/tests/__snapshots__/ContentAnalysisTest.js.snap
Remove conditional isOpen state variables
Add additional test for collapsed state snapshot
Update snapshots
* Changes the default state for Analysis headers to Collapsed instead of conditionally based upon the most important issues.
* Removed the value from the components when they match the default.
* Open the Analysis and see the headings being expanded.
* The headings should still be collapsible.
Fixes #430
> Change initial state to Open

- README.md
- package.json
* Made `react-intl` a peer dependency, and updated the documentation to inform users they should implement `react-intl`'s `IntlProvider` to use `yoast-components`.
*
Fixes #
> Make react-intl peer dependency

- composites/OnboardingWizard/Header.js
- composites/OnboardingWizard/OnboardingWizard.js
* Fixes a bug where a console warning is given if an function is given as icon.
* You can best test this against: https://github.com/Yoast/wordpress-seo/pull/9171
Fixes #438
> Use func proptype for icons

- composites/Plugin/Shared/components/Collapsible.js
- composites/Plugin/Shared/tests/__snapshots__/CollapsibleTest.js.snap
* The collapsible panel now uses up/down arrows instead of the right/down arrows it used to use. Also made sure the direction of the arrows matches gutenberg.
I tried quickly scaling down the size of the arrows, but couldn't find out quickly how to do it best. If anyone has any suggestions how to scale down svg images, please tell.
* The gutenberg dashicons won't be used in this pull yet, because they're not available outside gutenberg yet.
* Check if the arrows in this branch match the arrows used on the post page by gutenberg.
Fixes #463
> Collapsible panel using up/down

- app/SidebarCollapsibleWrapper.js
- composites/Plugin/Shared/components/Collapsible.js
- composites/Plugin/Shared/tests/CollapsibleTest.js
- composites/Plugin/Shared/tests/__snapshots__/CollapsibleTest.js.snap
* Added an optional ScreenReaderText after the Collapsible title.
* Used ScreenReaderText Component to add text to the title instead of an `aria-label` on the SvgIcon. Props to @afercia 
* The normal `yarn install && yarn start`.
* Go to `localhost:3333` and then click on the right most button `Sidebar Collapsible`.
* Activate a screenreader (`⌘ + F5` on a mac) and the top one should have an extra text.
Fixes #450
> Optional ScreenReaderText after the Collapsible title

- .eslintrc
- composites/Plugin/Shared/components/A11yNotice.js
- composites/Plugin/Shared/components/Checkbox.js
- composites/Plugin/SnippetPreview/components/SnippetPreview.js
- forms/Label.js
* Adds the jsx-a11y eslint plugin. 
(The actual adding of the eslint plugin was done in a PR that was accidentally pushed to develop)
*   A wrapping label is not necessary when there already is an htmlFor attribute. Therefore, only the id/htmlFor is required. This has been discussed with @afercia.
* Run `grunt eslint` and see there are no eslint errors from jsx-a11y.
> Configure label-has-for eslint rule

- composites/Plugin/Shared/tests/CheckboxTest.js
- composites/Plugin/Shared/tests/__snapshots__/CheckboxTest.js.snap
- grunt/config/eslint.js
* N/A
* I removed the console logs from the checkbox test, and mocked the onClick function instead. 
* I removed duplicate tests and snapshots that didn't add value. 
* I set the max-warnings in the eslint config to 0 🎉. When there are 1 or more warnings, eslint will throw: `Warning: ESLint found too many warnings (maximum: 0) Use --force to continue.`. I did not remove the option altogether, because in that case eslint won't throw a warning when there are 1 or more warnings.
* Run `yarn test` and see that the console logs are gone.
Fixes #471
> Remove console logs from Checkbox test

- composites/Plugin/Shared/tests/SvgIconTest.js
- forms/StyledSection/tests/__snapshots__/styledSectionTest.js.snap
- forms/StyledSection/tests/styledSectionTest.js
* N/A
* I've mocked the warning to prevent it from turning up in the console when running `yarn test`. 
* Run yarn test. Make sure all tests pass and no console warning is shown.
Fixes #469
> Move svgIcon warning test and use mock

- css/all.scss
* Removes old references in `all.scss` that caused build errors (a new release is needed as soon as possible).
* Run yarn install and grunt build
* The build should complete without errors
> Remove obsolete references in all.scss

- app/ContentAnalysisWrapper.js
- composites/Plugin/ContentAnalysis/components/ContentAnalysis.js
- composites/Plugin/ContentAnalysis/tests/ContentAnalysisTest.js
- composites/Plugin/ContentAnalysis/tests/__snapshots__/ContentAnalysisTest.js.snap
- composites/Plugin/Shared/components/HelpText.js
- composites/Plugin/Shared/tests/HelpTextTest.js
- composites/Plugin/Shared/tests/__snapshots__/HelpTextTest.js.snap
* Added a help text component.
* Uses PropType one of to make it possible to pass the text in an array as well as just a string. In the array you can pass a link for example. This prop type is exported to be used in a component that uses HelpText.
* Uses a paragraph element with a default style as main parent.
* View the HelpText in action: `yarn start` -> `localhost:3333` -> tab `Content analysis`.
* Check `yarn test` && `grunt check`.
Fixes #476
> Add optional help text to contentanalysis

- composites/Plugin/SnippetEditor/components/SnippetEditor.js
- composites/Plugin/SnippetEditor/tests/SnippetEditorTest.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
- composites/Plugin/SnippetPreview/components/SnippetPreview.js
* Added an optional date prop to the SnippetEditor.
* Added as separate prop and not inside data because it does not represent an editable field.
* Run `yarn test`
Fixes https://github.com/Yoast/wordpress-seo/issues/9535
> Add date to snippet editor props

- package.json
- utils/makeOutboundLink.js
- yarn.lock
We will switch from react-intl to @wordpress/i18n. I will make small PRs that do this. This is the first PR that is required for all the others.
* Make sure the outbound link still works, I've tested this by looking in the source of the content analysis switch language message.
> Change translation method in makeOutboundLink

- composites/AlgoliaSearch/tests/__snapshots__/SearchResultDetailTest.js.snap
- composites/Plugin/Shared/tests/__snapshots__/LinkButtonTest.js.snap
- composites/Plugin/Shared/tests/__snapshots__/YoastLinkButtonTest.js.snap
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
- composites/Plugin/SnippetPreview/tests/__snapshots__/SnippetPreviewTest.js.snap
- package.json
- webpack.config.js
- yarn.lock
I upgraded the development app to use webpack 4, since this needed to happen some time in the future anyway and I got an error when I used `yarn install` because of an incompatible package with node 9.
* Upgrades webpack to version 4+
* Removed JSON-loader
* Set webpack mode to `development`
* Install dependencies
* Make sure the development app works as expected
Fixes #
> Upgraded webpack to 4.7

- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
- composites/Plugin/SnippetPreview/components/SnippetPreview.js
- composites/Plugin/SnippetPreview/tests/__snapshots__/SnippetPreviewTest.js.snap
* Fixes arrow not showing up next to mobile description on hover and selection.
*
*
Fixes #504
> CSS Solution for fixing the carret by the mobile description

- composites/Plugin/SnippetEditor/components/ModeSwitcher.js
- composites/Plugin/SnippetEditor/components/SnippetEditor.js
- composites/Plugin/SnippetEditor/components/SnippetEditorFields.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
- composites/Plugin/SnippetPreview/components/ProgressBar.js
- composites/Plugin/SnippetPreview/components/SnippetPreview.js
- composites/Plugin/SnippetPreview/tests/__snapshots__/ProgressBarTest.js.snap
- composites/Plugin/SnippetPreview/tests/__snapshots__/SnippetPreviewTest.js.snap
Multiple styling changes to make the snippet editor more closely match the original snippet editor.
* N/A
* Used a prop to allow for different heights, to create a bigger input field for the meta description.
* Changed button.extends to extends(button). This fixes the switcher style, but I am unsure why. 
* Install deps: `yarn install`.
* Link the yoast-components branch:
* In the yoast-components clone: `yarn link` (skip this step if already done before).
* In wordpress-seo clone: `yarn link yoast-components`.
* Checkout it's companion branch in wordpress-seo. https://github.com/Yoast/wordpress-seo/pull/9635
* Install and build yoast-components: `yarn install && yarn start`.
* …
> Fix styling react snippet editor

- app/SnippetEditorExample.js
- composites/Plugin/SnippetEditor/components/ControlledInput.js
- composites/Plugin/SnippetEditor/components/SnippetEditorFields.js
- composites/Plugin/SnippetEditor/tests/SnippetEditorTest.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
- composites/Plugin/SnippetPreview/components/ProgressBar.js
* Not applicable
*
* Make sure the slug inputfield looks and works as expected.
* Use a `%` character in the slug input field to verify it's not a DraftJS editor.
Fixes Yoast/wordpress-seo#9603
> Change slug field to input field instead of draftjs editor

- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
- composites/Plugin/SnippetPreview/components/SnippetPreview.js
- composites/Plugin/SnippetPreview/tests/SnippetPreviewTest.js
- composites/Plugin/SnippetPreview/tests/__snapshots__/SnippetPreviewTest.js.snap
* Not applicable
* Characters that were previously encoded by `node`'s `url.parse` are now no longer url encoded in the mobile preview's breadcrumbs.
* Create a slug containing some of the following characters (` `^{`(including space)).
* Make sure the characters are not percent encoded in the breadcrumbs preview in mobile mode.
Fixes #514
> Don't encode percent characters that are encoded by node's url.parse

- app/SnippetEditorExample.js
- composites/Plugin/SnippetEditor/components/SnippetEditor.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
- composites/Plugin/SnippetPreview/components/SnippetPreview.js
Makes the `SnippetEditor` accept a locale prop that is passed down to the `SnippetPreview`.
Also changed the default locale from `en_US` to `en`.
* Not applicable
* 
* 
Fixes #518
> Pass locale prop from snippet editor to snippet preview

- composites/Plugin/SnippetEditor/constants.js
* N/A
* There was an error (see image) in a different PR related to the Snippet Editor replacevars.
* Navigate to pages with this branch and the PR on Wordpress-SEO checked out https://github.com/Yoast/wordpress-seo/pull/9678
* There should be no warning (compared to the old version of yoast-components).
**NOTE**: When this PR has been merged, yoast-components should be released and updated in wordpress-seo's (free and premium) package.json.
> Quick fix warning custom_field replacevars

- composites/Plugin/SnippetPreview/components/SnippetPreview.js
- composites/Plugin/SnippetPreview/tests/__snapshots__/SnippetPreviewTest.js.snap
Removes the keyword highlighting from the desktop url in the snippet preview.
* Not applicable
*
* In the old change the props in `SnippetEditorExample` so that the `keyword` appears in the `url` as a separate word (eg. `keyword: "welcome"` and `url: "https://local.wordpress.test/welcome-to-the-gutenberg-editor-2/"`). Make sure the keyword is highlighted in the snippet editor.
* Switch to this branch and make sure the keyword is no longer highlighted.
Fixes #524
> Remove keyword highlighting from desktop url

- app/SnippetEditorExample.js
- composites/Plugin/SnippetEditor/components/ReplacementVariableEditor.js
- composites/Plugin/SnippetEditor/serialization.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/ReplacementVariableEditorTest.js.snap
- composites/Plugin/SnippetEditor/tests/serializationTest.js
- package.json
- yarn.lock
* N/A
* Updated `draft-js-mention-plugin` to get rid of the console warning.
*  Refactored `serialize` and `unserialize`. Partly for the major version upgrade. And partly for the marking issue.
* Now passes the tags along to ignore non-tag affix matches.
* Run the tests.
* Check in the stand-alone.
* Link with the plugin and test.
Fixes https://github.com/Yoast/wordpress-seo/issues/9684 and https://github.com/Yoast/wordpress-seo/issues/9653
> Update DraftJS Mention Plugin.

- composites/Plugin/SnippetEditor/components/SnippetEditor.js
- composites/Plugin/SnippetPreview/components/SnippetPreview.js
* N/A
* We decided to add a placeholder for the description to be passed as a prop, to which the description should default if it is empty.
* Checkout wordpress-seo PR: 
* Link yoast-components (checked out to this branch).
* See that the snippet preview shows the placeholder when you empty the meta description in the snippet editor.
Fixes #https://github.com/Yoast/wordpress-seo/issues/9736
> Add metadescription placeholder

- composites/Plugin/SnippetEditor/components/SnippetEditor.js
* Replace the replace vars before measuring the title and description length to get the correct length.
- The replaceVariables function from the global is declared twice. When I put it on top of the file, it (obviously) couldn't be found, but the constructor was not a good location either. Suggestions are welcome, but please don't spend too much time.
> Replace replace vars before measuring the title and description length

- composites/Plugin/SnippetEditor/components/ReplacementVariableEditor.js
* Fixes a problem with the Snippet Editor where it would crash when receiving new content.
* Unserialize the new content in componentWillReceiveProps.
* Add extra check to test equality for when we received the old content as if it was new.
* Add ReplacementVariables to the componentWillReceiveProps as well to work correctly with the changing custom fields replacement variables.
* In the standalone app, it should no longer crash immediately after changing the title.
* In combination with the Yoast SEO plugin:
- Test if you no longer see the JS Error (did not occur always like in the standalone).
- When you add, update or remove a custom field in a post you should see this reflected …
> Fix snippet editor JS error with invalid RawDraftContentState

- composites/Plugin/SnippetEditor/components/SnippetEditorFields.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
- composites/Plugin/SnippetPreview/components/SnippetPreview.js
- composites/Plugin/SnippetPreview/tests/__snapshots__/SnippetPreviewTest.js.snap
* Improve the Snippet Preview rendering with long text.
- unless I'm missing something, the description should have maximum 4 lines of text
- adjusts the max-height to a proper value, based on the line height
- also improves some indentation, as we shouldn't have lines with a mix of tab characters and spaces
- to test on the standalone version, I've merged develop so the fix from #539 is in
- run `yarn start` and go on localhost:3333
- first, observe the behavior in the title field
- depending on the text added, you may see the overflowing word appear for some milliseconds and then disappear (suggestion: try repeatedly with very short words)
- then compare with the description field behavior
- the max number of lines is 4: when …
> Fix snippet preview overflow with long text.

- composites/Plugin/SnippetEditor/components/SnippetEditorFields.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
- composites/Plugin/SnippetPreview/components/SnippetPreview.js
- composites/Plugin/SnippetPreview/tests/__snapshots__/SnippetPreviewTest.js.snap
* Better encode SVG images used as CSS background.
- replaces `encodeURI` with `encodeURIComponent`
- not 100% sure this is the best method but `encodeURI` does not encode, for example, `:`, `/`, `=`, and they need to be encoded to make Firefox and IE 11 happy
- `encodeURIComponent` encodes them, even though it still doesn't encode, for example, dots `.` and hyphens `-`
- regardless, it seems to work now
- on the standalone version, run `yarn start` and go to http://localhost:3333/
- please test with **all** browsers the carets are shown properly
I've tested it on:
mac Chrome, Firefox, Safari, Opera
windows IE 11, Edge, Chrome, Firefox
Note:
at some point I was getting an error on Edge, see screenshot below, but then it …
> Better encode the SVG carets in the snippet preview and editor

- composites/Plugin/SnippetPreview/components/SnippetPreview.js
* Fixes a bug where a translation would be executed too early.
If we translate upon loading the file we don't have a chance to load the translations before this point, resulting in a Jed error.
* Load the term edit page in WordPress with yoast-components linked
* You shouldn't see an error now.
Fixes https://github.com/Yoast/wordpress-seo/issues/9779
> Move translation to React render method

- composites/Plugin/SnippetEditor/components/ReplacementVariableEditor.js
- composites/Plugin/SnippetEditor/components/SnippetEditorFields.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/ReplacementVariableEditorTest.js.snap
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
- package.json
- yarn.lock
* Implemented [draft-js-single-line-plugin](https://github.com/icelab/draft-js-single-line-plugin) in order to keep the Draft-js Editor from creating new blocks on enter presses. This results in a single-line editor. This now affects both the `SEO title` input field, and the `Meta description` input field.
* Used [draft-js-single-line-plugin](https://github.com/icelab/draft-js-single-line-plugin) because preventing the default for Enter keydowns did not work.
* Run `yarn install` and start yoast components.
* Type a sentence in the input field, and make it very long. The editor should remain one line high.
* Try to press `Enter` in the input fields, this should not create new lines. …
> SEO title input field should be single line

- composites/Plugin/SnippetEditor/components/ReplacementVariableEditor.js
- composites/Plugin/SnippetEditor/components/SnippetEditor.js
- composites/Plugin/SnippetEditor/components/SnippetEditorFields.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/ReplacementVariableEditorTest.js.snap
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
* Adds a meta description placeholder text
* Adds a descriptionEditorFieldPlaceholder prop to the snippet editor that is passed along to the draftJS editor (the name of the variable is very long and can be changed but was specified in this way in order to avoid confusion with the already existing variable `descriptionPlaceholder`)
* The color of the placeholder text is currently a lighter shade of grey compared to how it is in the old snippet editor. An [issue](https://github.com/Yoast/wordpress-seo/issues/9874) has been created for that.
* Empty your title and meta description templates in SEO > Search Appearance > Content Types
* Go to the snippet editor, edit snippet, and empty …
> Pass meta description placeholder to editor

- composites/Plugin/SnippetEditor/components/ReplacementVariableEditor.js
- composites/Plugin/SnippetEditor/tests/ReplacementVariableEditorTest.js
* N/A
* Stopped using draftjs-mention's own default filter, and started using a self-made filter that has no limit on matches, and that only matches from the start.
* Test if the tests pass.
* Go to a replacevarseditorfield ( the title field of the snippet editor for instance)
* Type a `%` and check if all available replacevars are suggested.
* Type a character, and check if only those replacevars are suggested that start with that character.
Fixes #https://github.com/Yoast/wordpress-seo/issues/9891
> Only suggest replacevars starting with the search value.

- app/SnippetEditorExample.js
- composites/Plugin/SnippetEditor/components/SnippetEditor.js
- composites/Plugin/SnippetEditor/serialization.js
- composites/Plugin/SnippetEditor/tests/SnippetEditorTest.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
* Make the progress bars for the snippet title and description respond to the content of the input fields.
* Multiple spaces and spaces at the beginning and end of the snippet description are no longer taken into account anymore for the description length progress.
* Newlines in the snippet description are replaced by a space before being displayed in the snippet preview.
* Move the measurement of the title and description from `wordpress-seo` to `yoast-components` in order to make the progress bars work without a CMS-specific implementation.
* Remove the test sliders for the progress bars, because the progress bars now respond to the content of the input fields.
* Strip multiple spaces and spaces at the beginning and end of the …
> Snippet preview title and description progress measurement overhaul

- app/SnippetEditorExample.js
- composites/Plugin/SnippetEditor/components/ReplacementVariableEditor.js
- composites/Plugin/SnippetEditor/constants.js
- composites/Plugin/SnippetEditor/serialization.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/ReplacementVariableEditorTest.js.snap
- composites/Plugin/SnippetEditor/tests/serializationTest.js
* Changes replacement variable editor to automatically replace replacement variables with entities.
* This makes it possible to type or paste `%%title%%` and have it automatically be replaced by an entity. This makes for a much better user experience.
* Open the snippet editor in the yoast components examples.
* See that you can type %%title%% and it turns into an entity.
* See that you can paste `%%title%% %%post_type%% %%sep%%` and they all turn into entities.
Fixes Yoast/wordpress-seo#9820
Fixes Yoast/wordpress-seo#9778
> Serialize replacement variables on the fly

- composites/Plugin/SnippetEditor/components/ReplacementVariableEditor.js
- composites/Plugin/SnippetEditor/components/SnippetEditor.js
- composites/Plugin/SnippetEditor/components/SnippetEditorFields.js
- composites/Plugin/SnippetEditor/tests/ReplacementVariableEditorTest.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
Reverts Yoast/yoast-components#572
Based on feedback, this approach will no longer be used (will remove the relevant replace vars in wordpress-seo instead), and these changes are therefore reverted.
> Revert "Stories/9834 ditch snippet variables"

- composites/Plugin/SnippetEditor/components/SnippetEditor.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/ReplacementVariableEditorTest.js.snap
* N/A
* Uses the meta description date in the props to calculate actual length of the meta description
* Adds an additional 3 to the length if date is present, since two spaces and a hyphen (" - ") are automatically appended to the description date in that case
* Make sure that "date in snippet preview" is enabled for posts and pages (under "SEO" -> "Search Appearance" -> "Content types")
* In a post/page, edit the snippet and write a meta description that exactly fills the progress bar (i.e. the color is still green)
* Copy the description as it appears in the snippet preview (i.e. should include the date)
* Counting the characters (using appropriate program or website) should show …
> Account for the date when calculating meta description length

- composites/Plugin/SnippetEditor/components/SnippetEditorFields.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
* N/A
* Remove white-space nowrap style on the TitleInputContainer in the SnippetEditorFields. This was creating problems in other browsers than Chrome.
* https://github.com/Yoast/yoast-components/pull/568#issuecomment-395423015
* https://github.com/Yoast/yoast-components/pull/568#issuecomment-395426406
* https://github.com/Yoast/yoast-components/pull/568#issuecomment-395450196
* https://github.com/Yoast/yoast-components/pull/568#issuecomment-395452346
I did not test in IE and Edge to see if this fixes those yet.
> Fix single line browser compatibility

- package.json
- yarn.lock
* Bumps YoastSEO.js to 1.34.0
* Check whether nothing breaks.
> Bump YoastSEO.js to 1.34.0

- composites/Plugin/SnippetEditor/components/Mention.js
- composites/Plugin/SnippetEditor/components/ReplacementVariableEditorStandalone.js
- composites/Plugin/SnippetEditor/components/SettingsSnippetEditorFields.js
- composites/Plugin/SnippetEditor/components/Shared.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
* Change styling of Draft.js Mention Plugin entities. They now have a purple background, white letters, rounded corners, and more padding and margin. 
* I'm overwriting the mention component from the mention plugin to add styling to the mentions/entities.
* I've made the line height of the meta description input the same as the line height of the title input, to make the entities in both fields look the same.
* I've discussed the following styling changes (which were not in the issue) with @hedgefield:
- Less padding between the snippet editor input fields.
- Less padding between the bottom field and the close button.
- Align the bottom of the input field title with the bottom of the inserter button text.
- Remove the padding …
> Snippet editor and entities styling tweaks

- composites/Plugin/SnippetEditor/components/SnippetEditor.js
* Only add date to the length of the description if the description is set.
* Added an additional check so that date is not accounted for in the progress bar in cases of empty descriptions
* This is a bug fix and not directly related to the connected issue 
* In settings, make sure that Date in Snippet Preview is enabled
* Empty the meta description field
* The progress bar should be completely empty
* Typing a single character in the meta description should immediately take the length of the date into account
Fixes https://github.com/Yoast/wordpress-seo/issues/9985
> Fix progress bar for empty meta description

- composites/Plugin/SnippetEditor/components/ReplacementVariableEditor.js
- composites/Plugin/SnippetEditor/components/ReplacementVariableEditorStandalone.js
- composites/Plugin/SnippetEditor/components/SnippetEditorFields.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
* N/A
* Passes the OnBlur prop from the snippetEditor to the ReplacementVariableEditorStandalone, causing a blur event to now call the unsetFieldFocus function. This means that the active field is now correctly updated and the focus is correctly set on a click event.
* Edit a post/page, and edit snippet
* Click on the meta description field, underneath the part containing the text
* The field should be selected, with the text cursor being at the last character in the text
* Try different combinations (first clicking the focus keyword field before clicking the description field, first clicking the title, etc.), all of which should produce the above behavior
* Try the same in the …
> 9798 clickability meta description field

- composites/Plugin/SnippetEditor/components/Shared.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
* Improve the snippet editor placeholder color contrast
* Uses the same gray color we use on MyYoast
- currently, the placeholder text in the description field has a light gray color that becomes even lighter when the field is focused:
This PR changes the color to `#646464` in both states (normal and focused). 
- test the standalone version: `yarn-start` and go to localhost:3333
- open the snippet editor
- empty the description field to make the placeholder text appear
- check the placeholder color is always `#646464` also when the field is focused
- optionally, yarn-link to the  plugin `release-7.7` branch and test also in the plugin
Fixes #602 
Fixes https://github.com/Yoast/wordpress-seo/issues/9874
> Improve the snippet editor placeholder color contrast

- composites/Plugin/SnippetEditor/components/ReplacementVariableEditorStandalone.js
* Fixes an issue where in cases with a lot of snippet variables it would sometimes be partially hidden behind the WordPress toolbar.
* Increased the z-index by 1000, because this is the value of the element it was behind has as z-index.
* See issue.
Fixes https://github.com/Yoast/wordpress-seo/issues/10045
> Higher z-index for the mention plugin suggestions

- composites/Plugin/SnippetEditor/components/ReplacementVariableEditor.js
- composites/Plugin/SnippetEditor/components/ReplacementVariableEditorStandalone.js
- composites/Plugin/SnippetEditor/serialization.js
- composites/Plugin/SnippetEditor/tests/ReplacementVariableEditorTest.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/ReplacementVariableEditorTest.js.snap
- composites/Plugin/SnippetEditor/tests/serializationTest.js
* Replacevar suggestions now use nicenames rather than raw replacevariable names.
* Test whether the dropdown suggestion list (after typing `%`) uses nicenames, and will fill the nicename into the editor field.
* Verify that the preview still replaces the variable with the correct value.
* Save and load posts, and enter replacevars by just typing `%%title%%` etc., and see that that functionality also still works (so without using the mention/suggestions).
Fixes #577 
Requires https://github.com/Yoast/wordpress-seo/pull/10065 (for custom field replacevars)
> Use replacevar labels (nicenames) in suggestions

- composites/OnboardingWizard/components/Choice.js
- composites/Plugin/SnippetEditor/components/ReplacementVariableEditorStandalone.js
- composites/Plugin/SnippetEditor/serialization.js
- composites/Plugin/SnippetEditor/tests/ReplacementVariableEditorTest.js
- composites/Plugin/SnippetEditor/tests/serializationTest.js
- composites/basic/Loader.js
* [ReplacementVariableEditor] Handle cut and copy behavior in the replacement variable editor.
This change hooks into the browser copy and cut events. We then
serialize the part of editor that is currently selected if the editor is
focused. We try to put this serialized text into the clipboard data.
This means we can now copy and cut replacement variables from a
replacement variable editor.
* Open the editor
* Copy a piece of text that includes replacement variables.
* Paste this into another replacement variable editor.
* You should now have the same replacement variables.
* Paste this into a text editor or the URL input.
* You should now have the text with the variables replaced …
> Add serialized content to copy and cut

- composites/Plugin/SnippetEditor/components/SettingsSnippetEditor.js
- composites/Plugin/SnippetEditor/components/SnippetEditor.js
- composites/Plugin/SnippetEditor/components/SnippetEditorFields.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
- composites/basic/ErrorBoundary.js
* Introduce an ErrorBoundary component to be used for the Snippet Editor.
- for now, the error boundary wraps the SnippetEditorFields component
- it can be changed to wrap any other components tree, if desired
- uses `a11ySpeak` to deliver an audible message to screen reader users
Design feedback needed /Cc @hedgefield 
We can't predict where we'll need to re-use this component and show errors, so we can't set arbitrary paddings / margins. For this reason, I've aligned the text to the centre and used a bottom border, as it seemed the most pragmatical solution to me. Of course, this can be changed if desired, just let me know. Personally, I'd add `moar` white space. Screenshot:
You can test the standalone version or yarn-link to the plugin:
- with Microsoft Edge on Windows: select the …
> Introduce an ErrorBoundary component and use it around the SnippetEditorFields

- composites/Plugin/SnippetEditor/components/Shared.js
- composites/Plugin/SnippetEditor/components/SnippetEditor.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
* Moves the margin bottom from the FormSections to the CloseSnippetEditor button.
* N/A
* Ensure the snippet editor margins / paddings look the same on the metabox.
* On the settings pages this will solve a to-much-margin-at-the-bottom error from @jcomack
> Move margin bottom of the form section to the close editor snippet button

- composites/Plugin/SnippetEditor/components/SnippetEditor.js
- composites/Plugin/SnippetEditor/tests/SnippetEditorTest.js
* Changes in replacevariables now cause progress in SEO Title and description to be measured with the new replacevariable values.
* I chose to optionally pass replacementVariables to `mapDataToMeasurements` (and eventually `processReplacementVariables`), so that when mapDataToMeasurements is accessed from the `componentWillReceiveProps` function, the "next" replacementVariables can be used.
* Put `%%title%%` in the SEO Title input field.
* Change the title of the post. See that the progress changes accordingly.
* Do the same for the description (put `%%title%%` in it and change the title).
* It should work for any replacement variable that you change, and that is placed in the title …
> Pass updated replacementvariables when measuring progress

- composites/Plugin/SnippetEditor/components/ReplacementVariableEditor.js
- composites/Plugin/SnippetEditor/components/SettingsSnippetEditorFields.js
- composites/Plugin/SnippetEditor/components/Shared.js
- composites/Plugin/SnippetEditor/components/SnippetEditorFields.js
- composites/Plugin/SnippetEditor/tests/SnippetEditorTest.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
Fixes the “insert snippet variable” button alignment by using only CSS and removing any JS widths calculation.
- Flexbox
- the "labels" have a min-width of 200 pixels, this should give enough room for longer translations on narrow screens; on large screens, the labels are allowed to grow
- in the standalone version you can test just the meta box snippet editor
- in order to test also the Settings pages variables editor, you need to yarn-link to the plugin branch `release/7.7` and test in the plugin
- test the button is aligned horizontally with the labels on large screens
- on small screens the button should go below the label
- note: currently there's an issue with the "Archives > Special pages" section, we'll see if there's a way to fix it
Fixes #594 
Fixes #583
> Simplify replacement variable insert button alignment.

- composites/Plugin/SnippetEditor/components/ReplacementVariableEditorStandalone.js
* Fixes an issue where, when using a RTL language, the snippet variable suggestions would disappear behind the admin menu.
* Increase z-index of the suggestions container by 9990.
* In combination with the plugin, set an RTL language in WordPress.
* Open the snippet editor and insert `%` to open the suggestions (see screenshot of issue).
* Verify the suggestions are on top of the admin menu.
Quickly fixes #10179
> Fix RTL suggestions by increasing the z-index

- composites/Plugin/SnippetEditor/components/ModeSwitcher.js
- composites/Plugin/SnippetEditor/components/Shared.js
- composites/Plugin/SnippetEditor/components/SnippetEditor.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
- composites/Plugin/SnippetPreview/components/HelpTextWrapper.js
- composites/Plugin/SnippetPreview/components/SnippetPreview.js
- forms/StyledSection/StyledSection.js
- forms/StyledSection/tests/__snapshots__/styledSectionTest.js.snap
- index.js
- utils/helpers/styled-components.js
* Fix the styling of the ModeSwitcher, SnippetEditor, HelpTextWrapper, SnippetPreview and StyledSection for right-to-left languages. 
* Introduce `getRtlStyle` function to determine which style to use. 
* See https://github.com/Yoast/wordpress-seo/pull/10189
Fixes https://github.com/Yoast/wordpress-seo/issues/10174
> Fix components styling for RTL languages

- composites/Plugin/SnippetEditor/components/ReplacementVariableEditor.js
- composites/Plugin/SnippetEditor/components/ReplacementVariableEditorStandalone.js
- composites/Plugin/SnippetEditor/components/__mocks__/ReplacementVariableEditorStandalone.js
- composites/Plugin/SnippetEditor/tests/ReplacementVariableEditorTest.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/ReplacementVariableEditorTest.js.snap
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
* Adds Styled Component's `withTheme` to the `ReplacementVariableEditorStandalone` component in order to set the `textDirectionality ` of the `Editor` based on the language direction that is passed to the theme.
* Add RTL theme to snippet editor
* See https://github.com/Yoast/wordpress-seo/pull/10224
Fixes https://github.com/Yoast/wordpress-seo/issues/10208
> Add rtl theme to snippet editor

- composites/Plugin/SnippetEditor/components/ReplacementVariableEditor.js
- composites/Plugin/SnippetEditor/tests/SnippetEditorTest.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
* Fixes a bug where console errors would be thrown because `ref` instead of `innerRef` was used in the `ReplacementVariableEditor`.
> Remove ref to solve console error

- composites/Plugin/SnippetEditor/components/ReplacementVariableEditor.js
- composites/Plugin/SnippetEditor/components/SettingsSnippetEditor.js
- composites/Plugin/SnippetEditor/components/SettingsSnippetEditorFields.js
- composites/Plugin/SnippetEditor/components/SnippetEditorFields.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
Adds ID's to elements. For the purpose of testing via puppeteer.
* Adds the id "snippet-editor-field-title" to the inputcontainer, before draft.js is used.
* Adds the id "snippet-editor-field-slug" to the input element the slug is in.
* Adds the id "snippet-editor-field-description" to the inputcontainer, before draft.js is used.
**Branched from release/7.7, we should wait until the release of 7.7 before merging this one**
* N/A.
* Sets the id for the slug at the input field of the slug.
* Sets the id "snippet-editor-field-title" and the id  on the inputContainer component, before draft.js is used.
* Edit Maarten: came across an oversight with the onBlur functionality which caused some weird behavior with clicking a focused …
> Sets static ids on elements close to the input fields

- composites/Plugin/SnippetEditor/components/__mocks__/ReplacementVariableEditorStandalone.js
- composites/Plugin/SnippetEditor/tests/SnippetEditorTest.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
* N/A
* Introduced a wrapper in the mock for ReplacementVariableEditorStandalone which passes `innerRef` as a `ref`. ReplacementVariableEditorStandalone needs the ref prop because the `focus` function needs it.
* Re-enable tests that are dependent on this mock.
* Run `yarn test` and check that all tests pass.
> Introduce wrapper in mock to pass innerRef as a ref and re-enable tests

- composites/Plugin/ContentAnalysis/tests/__snapshots__/AnalysisCollapsibleTest.js.snap
- composites/Plugin/ContentAnalysis/tests/__snapshots__/ContentAnalysisTest.js.snap
- composites/Plugin/Shared/components/Button.js
- composites/Plugin/Shared/tests/__snapshots__/ButtonTest.js.snap
- composites/Plugin/Shared/tests/__snapshots__/CollapsibleTest.js.snap
- composites/Plugin/Shared/tests/__snapshots__/LinkButtonTest.js.snap
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
- composites/Plugin/SnippetPreview/tests/__snapshots__/HelpTextWrapperTest.js.snap
- composites/Plugin/SnippetPreview/tests/__snapshots__/SnippetPreviewTest.js.snap
* Fix the CSS media query to target IE11 used for the buttons min-height
- for the media query to work and target IE11, there shouldn't be spaces within brackets
- pairs with what was already done for the `YoastButton` component
- best way to test this in IE11 is to increase the `settings.minHeight` value for both the `Button` and `YoastButton` components
- you should then add the buttons somewhere in the standalone examples but there's really no need for it, I've already tested it and the PR just removes a few spaces
Aside: I'd like to propose to add a page to the standalone App to test all the buttons.
Before:
After:
Fixes #633
> Fix min-height CSS hack for buttons in IE11.

- README.md
- app/configureStore.js
- composites/Plugin/ContentAnalysis/actions/contentAnalysis.js
- composites/Plugin/ContentAnalysis/actions/tests/ContentAnalysisTest.js
- package.json
* Removes the unused `replaceKeyword` action.
* The `replaceKeyword` action was not used in either wordpress-seo or yoast-components. 
* This was the only action that needed redux-thunk, so I removed that dependency as well.
* Link this branch to `wordpress-seo`. 
* Run `yarn test` and see that all tests pass.
* Go to the metabox in the plugin. Open Redux Devtools and look for our store. Change the keyword in the metabox, and see that the keyword is still updated correctly.
> Remove unused replaceKeyword

- composites/Plugin/SnippetEditor/components/__mocks__/ReplacementVariableEditorStandalone.js
* N/A
* innerRef is a function, not a string.
* Run the tests and see that the following error has disappeared:
> Fix propType of innerRef in mock

- App.js
- app/ButtonsWrapper.js
Adds a buttons test page to the examples standalone app
The intent of this page is to have a place where to check all the different buttons we have in yoast-components and allow to check they work correctly (at least visually). For example, it would have been useful to have this to prevent some regressions, see #631, #632, and #633.
Please check if I've missed any button type (they can always be added later if needed)
Fixes #647
> Add buttons page

- app/SnippetEditorExample.js
* Fixes an error in the snippet editor standalone example
- uses ThemeProvider to pass a theme prop with a proper `isRtl` setting
- `isRtl` is handled in the state
- adds a button to switch language direction in the editor, thought this was a nice-to-have for testing
Notes:
- the language switch is not immediately applied to the replacement variable editors, not sure why; there's the need to click on them or click the preview elements to trigger the re-rendering
- consider this switches the language just on the draft.js editors and for components that use the state `isRtl` property; for a proper, full, language direction switch many other things are needed for example setting a `dir` attribute on the document
- for the future: …
> Add ThemeProvider to pass a language direction prop to the editor example

- composites/HelpCenter/views/VideoTutorial.js
- composites/HelpCenter/views/tests/VideoTutorialTest.js
- composites/HelpCenter/views/tests/__snapshots__/VideoTutorialTest.js.snap
* Fixes alignment of video in help center when no ads are present.
* Added a prop based on VideoContainer determining whether or not there are ads present. 
* Checkout this branch.
* Run `yarn install` on this branch.
* Link this branch to WordPress SEO Premium. ( run`yarn link` in this branch, and run `yarn link yoast-components` in wordpress-seo-premium.
* Go to the help center, first tab: "Video Tutorial" and see that the video is now correctly aligned in the center. 
* Follow the same steps for WordPress SEO to make sure the alignment is still to the left and allows space for advertisements on the right side. 
Fixes #[10106](https://github.com/Yoast/wordpress-seo/issues/10106)
> Changed video alignment in help center when no ads present

- package.json
- yarn.lock
* Bumps YoastSEO.js to 1.36.0
* Check whether nothing breaks.
> Bump YoastSEO.js to 1.36.0

- composites/LinkSuggestions/LinkSuggestions.js
- index.js
- package.json
- utils/index.js
- yarn.lock
* We now expose makeOutboundLink, inside a utils object.
* Added `Clipboard` and `a11y-speak` to the `package.json` because tests were failing.
* We needed makeOutboundLink() in wordpress-seo, but were asked by @atimmer to not use paths when importing. Thus, we needed to expose makeOutboundLink in a `utils/index.js` file.
* Checkout this branch and verify that all tests succeed, also when linking to wordpress-seo.
Fixes #661
> Expose makeOutboundLink for UpsellBox in wpseo

- app/KeywordExample.js
- composites/Plugin/Shared/components/SynonymsInput.js
- composites/Plugin/Shared/components/YoastInput.js
- index.js
* SynonymsInput field now looks similar to the `KeywordInput`, and can have an explaniontext below the label.
* Needed to reuse the KeywordInput for the SynonymsInput, but found it was too specific. So we extracted some stuff and created a new SynonymsInput from the extracted components. This does not affect the existing inputs.
* Checkout branch, and run `yarn start`.
* Verify in the examples (under "Keyword") that the new SynonymsInput functions and looks as expected: it should have a label, a text below the label, and a functioning input field.
Connects https://github.com/Yoast/yoast-components/issues/660
> Extract yoast input field

- index.js
* Exposes all exports needed by wordpress seo to the export file.
* Adding all exports in the main `index.js` since the directory format is somewhat weird
* Use the library in the plugin and make sure the added exports work as expected.
Needed for: https://github.com/Yoast/wordpress-seo/issues/10478
> Add all imports needed by wordpress seo to the export file.

- composites/Plugin/ContentAnalysis/components/ContentAnalysis.js
- composites/Plugin/ContentAnalysis/tests/__snapshots__/ContentAnalysisTest.js.snap
- composites/Plugin/CornerstoneContent/components/CornerstoneToggle.js
- composites/Plugin/CornerstoneContent/tests/__snapshots__/CornerstoneToggleTest.js.snap
- composites/Plugin/Shared/components/Collapsible.js
- composites/Plugin/Shared/components/Toggle.js
- composites/Plugin/Shared/tests/__snapshots__/CollapsibleTest.js.snap
- composites/Plugin/SnippetEditor/components/ModeSwitcher.js
- composites/Plugin/SnippetEditor/components/SnippetEditor.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
- composites/Plugin/SnippetPreview/components/SnippetPreview.js
- composites/Plugin/SnippetPreview/tests/__snapshots__/SnippetPreviewTest.js.snap
* _N/A_
* Added `!important` to `h2` overrides in the Collapsible, otherwise the styling of the `#postbox h2` in WordPress will not be changed - these can be seen in the components in the metabox.
* Added `hasPadding` to the Collapsible, to make the content of the collapsible to have padding and the internal items have no padding.
* Added `hasSeparator` to the Collapsible to make borders around the entries to have them visually separated
* Use the PR (https://github.com/Yoast/wordpress-seo/pull/10483) on Yoast SEO to see the changes.
Fixes #671
> Styling improvements

- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
- composites/Plugin/SnippetPreview/components/SnippetPreview.js
- composites/Plugin/SnippetPreview/tests/__snapshots__/SnippetPreviewTest.js.snap
* Removes help button from SnippetPreview
*
* Test in combination with https://github.com/Yoast/wordpress-seo/pull/10542
Fixes Yoast/wordpress-seo#10527
> Removed HelpTextWrapper from SnippetPreview

- composites/Plugin/Shared/components/SynonymsInput.js
* Increases the synonyms explanation text size and changes color
- also removes a redundant aria-label
- check the text is bigger (inherits 13 pixels in WordPress) and color is `#646464`
To test in the plugin, the process is a bit more articulated:
- switch the plugin to the branch release/8.0 to avoid the babel error
- `yarn link yoast-components` just in the root
- cd to the premium folder and build the JS
- no need to build the JS in the root
Fixes #688
> Change synonyms explanation text size and color

- composites/Plugin/SnippetPreview/components/SnippetPreview.js
* Removed the helpTextButton from the SnippetPreview as it has been replaced by a description that is always present. 
* Check out this branch, see that the helpTextButton now (really) is gone. 
Fixes #698
> Removed helpTextButton from SnippetPreview

- composites/Plugin/Shared/components/KeywordInput.js
- composites/Plugin/Shared/tests/__snapshots__/KeywordInputTest.js.snap
* Added support for onblur event on an additional keyword input field.
* Follow the steps in https://github.com/Yoast/wordpress-seo-premium/pull/1922
Fixes #[1921](https://github.com/Yoast/wordpress-seo-premium/issues/1921)
> Implement onblur event

- composites/Plugin/Shared/components/Button.js
- composites/Plugin/Shared/components/SvgIcon.js
* N/A
* Link `yoast-components` to `wordpress-seo` and build the project.
* Open a post in gutenberg in the plugin, open the Yoast SEO sidebar and make sure the warning is no longer given.
Fixes Yoast/wordpress-seo#10672
> Fix invalid icon warning when no icon is provided to IconsButton

- package.json
- yarn.lock
* n/a
##Relevant technical choices:
* Bumps YoastSEO.js to 1.36.0
* Check whether nothing breaks.
> Bump YoastSEO.js to 1.39.0

- composites/Plugin/ContentAnalysis/components/AnalysisList.js
- composites/Plugin/ContentAnalysis/components/ContentAnalysis.js
- composites/Plugin/ContentAnalysis/tests/__snapshots__/ContentAnalysisTest.js.snap
- index.js
* Exposes `AnalysisList` to render a plain list of content analysis results.
* Exposes `renderRatingToColor` which renders a rating received from YoastSEO.js to a color that can be used in CSS.
* This makes it possible to use the plain list without the headings in different project. I specifically needed it for the YoastSEO.js dev tool.
* Open the standalone test tool of yoast-components.
* Verify that the content analysis looks and works the same as before.
* Run the unit tests.
* Verify they pass.
> Refactor ContentAnalysis to expose AnalysisList

- package.json
- yarn.lock
* n/a
* Bumps YoastSEO.js to v. 1.39.2
*Check whether nothing breaks.
> Bump YoastSEO.js to 1.39.2

- composites/Plugin/SnippetEditor/components/SnippetEditor.js
* Fixes a bug where the placeholder "Modify your meta description by editing it right here" wasn't translatable.
* The translation is just missing, thus it isn't really testable. If it looks okay, please merge.
> Makes the string translatable

- composites/Plugin/Shared/components/LanguageNotice.js
Otherwise the textdomain is not available yet and the text will not be translated.
Resolves the "textdomain 'yoast-components' not found"
* _N/A_
*
* Load a post-edit page and see no error about the textdomain appear.
* The text should be translated in the metabox readability analysis section
Fixes #
> Load translation inside lifecycle function

- app/SnippetEditorExample.js
- composites/Plugin/SnippetEditor/components/SnippetEditor.js
- composites/Plugin/SnippetEditor/serialization.js
- composites/Plugin/SnippetPreview/components/SnippetPreview.js
- package.json
- yarn.lock
Fix /js references to /src
Loads the `YoastSEO.js` release branch.
This needs to be set to the version that is released before release.
* _N/A_
*
*
Fixes #
> Reference YoastSEO.js release branch

- composites/Plugin/Shared/components/KeywordInput.js
- composites/Plugin/Shared/tests/__snapshots__/KeywordInputTest.js.snap
* Renamed 'Focus keyword' to 'Focus keyphrase' in the `KeywordInput` component.
* After discussing with Joost, I didn't change the following string: "Read our %1$sultimate guide to keyword research%2$s to learn more about keyword research and keyword strategy."
* Link this branch to Free using `yarn link` (the components example is currently broken).
* Check in both the metabox and the sidebar that the keyword input label has changed to 'focus keyphrase'
Fixes #738
> Rename keyword to keyphrase in the KeywordInput component

- app/SnippetEditorExample.js
- composites/Plugin/SnippetEditor/components/SnippetEditor.js
Fixes the snippet preview demo in the standalone app.
To test:
- check the standalone app: `yarn start` and go to `localhost:3333`
- go in the Snippet preview tab
- verify there are no errors and the snippet preview / editor work as expected
- edit the meta description and verify the progress bar works as expected (max length is 156 characters)
Note: since the date in the meta description demo is hardcoded (`Jan 8, 2018 -`) you can actually enter only 143 characters before the progress bar turns into orange.
Fixes #740
> Fix import in the Snippet Preview demo.

- composites/Plugin/Shared/components/KeywordInput.js
- composites/Plugin/Shared/components/SynonymsInput.js
* N/A
Updates the SynonymsInput to not use an help text any longer and use a help link icon instead.
Fixes https://github.com/Yoast/wordpress-seo-premium/issues/2058
> Update SynonymsInput to use a help link.

- package.json
- yarn.lock
* n/a
* Bumps YoastSEO.js to v. 1.41.1
* Check whether nothing breaks.
> Bump YoastSEO.js to 1.41.1

- composites/Plugin/SnippetEditor/components/ReplacementVariableEditorStandalone.js
Fixes https://github.com/Yoast/wordpress-seo/issues/11482
See https://github.com/Yoast/yoast-components/pull/749
* N/A
- removes the `id` prop from the draft.js `Editor` as it's not an allowed prop and it doesn't do anything
- removes a try/catch statement from the `setEditorRef()` function: this statement tried to set an `id` to the draft.js editable field using DOM methods:
- not sure why we should try to set the `id` here, as it's already set by `setEditorFieldId()` when the component mounts. The whole statement seems safe to remove to me, unless I'm missing something.
- worth noting when a component gets unmounted, React runs something called `safelyDetachRef` which calls the ref callback and the DOM method used there failed, …
> Simplify replacement variable editor logic to set id and ref.

- package.json
- yarn.lock
* n/a
* Bumps YoastSEO.js to v. 1.42.0.
* Follow [these testing steps](https://github.com/Yoast/Wiki/wiki/Testing-YoastSEO.js-version-bumps-on-Yoast-Components) and see whether nothing breaks.
> Bump YoastSEO.js to 1.42.0

- package.json
- yarn.lock
* n/a
* Updates YoastSEO.js to 1.43.0.
* Check whether nothing breaks; see also https://github.com/Yoast/Wiki/wiki/Testing-YoastSEO.js-version-bumps-on-Yoast-Components
> Bump YoastSEO.js to 1.43.0

- utils/buildStructuredUrl.js
- utils/index.js
- utils/tests/buildStructuredUrlTest.js
* Adds `buildStructuredUrl` function.
* This is the first step towards fixing Yoast/wordpress-seo#3514. It introduces a function that later on will be used to built the permalink in the snippet editor.
* Link `yoast-components` with this PR to `wordpress-seo` and build the project.
* In your browsers console go to any admin page where `window.yoast.components` is loaded, like the Dashboard.
* In the console, you can test the function, for example like this:
```
window.yoast.components.utils.buildStructuredUrl( "http://www.example.com/%category%/%postname%", {
category: [ "transportation", "flying" ],
postname: "the-cost-of-flying",
} );
```
Fixes #780 
[Edit by Andrea]
Changed …
> 780 build structured url api

- composites/Plugin/Shared/components/KeywordInput.js
- composites/Plugin/Shared/components/SynonymsInput.js
- composites/Plugin/Shared/tests/__snapshots__/KeywordInputTest.js.snap
* Add onBlur and onFocus prop to SynonymsInput component.
* N/A
* Test in combination with https://github.com/Yoast/wordpress-seo/pull/11728
Fixes Yoast/wordpress-seo/issues/11710
> Add onBlurSynonym to SynonymsInput component

- app/ComponentsExample.js
- composites/Plugin/Shared/components/KeywordInput.js
- composites/Plugin/Shared/components/SynonymsInput.js
- composites/Plugin/Shared/tests/YoastWarningTest.js
- composites/Plugin/Shared/tests/__snapshots__/KeywordInputTest.js.snap
- grunt/config/eslint.js
Keyphrase and Synonyms input fields
* Removes autocomplete functionality from the Keyphrase and Synonyms input fields.
*
* Inspect the Keyphrase and Synonyms input fields and see the `autocomplete="off"` being added as HTML attributes
* See issue for other test step
Fixes #792
> Add autocomplete directive to keyphrase fields

- package.json
- yarn.lock
* n/a
* Updates YoastSEO.js to 1.44.0.
* Check whether nothing breaks; see also https://github.com/Yoast/Wiki/wiki/Testing-YoastSEO.js-version-bumps-on-Yoast-Components
> Bump YoastSEO.js to 1.44.0

- app/ComponentsExample.js
- app/DashboardWidgetWrapper.js
- composites/Plugin/DashboardWidget/components/WordpressFeed.js
- composites/Plugin/DashboardWidget/tests/__snapshots__/WordpressFeedTest.js.snap
- package.json
- utils/getFeed.js
- yarn.lock
* Fixes parsing of feeds in Internet Explorer 11
- uses [Wicked Good XPath](https://github.com/google/wicked-good-xpath) for browsers that don't support XPath evaluation (IE11), for more details see their documentation. I'm not an expert in XPath parsing in JS, but it works. /Cc @atimmer @herregroen 
- adds a real dashboard widget working example in the demos
Updated instructions:
- at the moment, this PR can't be tested in the standalone app because of https://github.com/Yoast/YoastSEO.js/issues/2086
- if you want to test it there, you need to downgrade `yoastseo` to `v1.43.0` in the package.json
- first, test on `release-yoast-seo/9.5`
- go to the WP dashboard and observe in IE11 the Yoast dashboard widget doesn't show the …
> Make getFeed work in IE11 and Edge

- composites/Plugin/Shared/components/Collapsible.js
- composites/Plugin/Shared/components/SvgIcon.js
- composites/Plugin/Shared/tests/__snapshots__/CollapsibleTest.js.snap
* Uses the same chevrons as Gutenberg does.
* 
* Checkout wordpress-seo/trunk
* Link this branch (`yarn link`)
* Do the grunt building happiness
* Compare the arrows (chevrons) in the Yoast sidebar with the one that Gutenberg uses
* Note: the metabox is using the old style because of this is WordPress internal logic and it's too hard to change that:
Fixes https://github.com/Yoast/wordpress-seo/issues/11490
> Use the Gutenberg chevrons

- package.json
- yarn.lock
* Upgrade webpack-dev-server to 3.1.14
* N/A
* `yarn install && grunt build:js && grunt build:css`: see no errors
* `yarn start`: see no errors
* Go to `http://localhost:3333`: see a working example with no console errors.
Fixes #
> Upgrade webpack-dev-server to 3.1.14

- composites/Plugin/ContentAnalysis/components/AnalysisList.js
Related keyphrases and the focus keyphrase can apply the same assessments. The active marker needs differentiating between the analysis results. Therefore, this PR changes the pressed check to a freshly introduced `markerId`.
* Change AnalysisList pressed status check to listen to `result.markerId` instead of `result.id`.
*
* See related PR: https://github.com/Yoast/wordpress-seo-premium/pull/2181
Fixes https://github.com/Yoast/YoastSEO.js/issues/2011
> Related keyphrase marking

- webpack.config.js
IE11 does not support destructuring of assignments (or any destructuring https://kangax.github.io/compat-table/es6/#ie11).
Use Babel to transpile this to IE11 understandable code.
* [non-user-facing] Fixes the standalone in IE11.
* Adds an exception for `node_modules/yoastseo` in the babel exclusion of the webpack config.
* use IE11
* on `yoast-components`, run `yarn` to make sure everything is updated
* run `yarn start` and go to the standalone demos on [http://localhost:3333](http://localhost:3333/)
* open the IE11 console (press F12)
* note that the IE11 console needs to be open, this is a pre-existing issue: without opening the console you won't see anything
Ensure you no longer …
> Babelify YoastSEO.js in the standalone

- package.json
- yarn.lock
* [non-user-facing] Version bump for YoastSEO (to 1.47.0)
* N/A
* See: https://github.com/Yoast/Wiki/wiki/Testing-YoastSEO.js-version-bumps-on-Yoast-Components
Fixes #
> Bumped YoastSEO version to 1.47.0

- composites/Plugin/SnippetEditor/components/SnippetEditor.js
- composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
- composites/Plugin/SnippetPreview/components/SnippetPreview.js
- composites/Plugin/SnippetPreview/tests/SnippetPreviewTest.js
- composites/Plugin/SnippetPreview/tests/__snapshots__/SnippetPreviewTest.js.snap
* [not-user-facing] Adds `keywordForms` field to SnippetPreview and SnippetEditor, to be able to highlight word forms of the keyphrase the preview.
*
* See https://github.com/Yoast/wordpress-seo/pull/12106
Fixes #https://github.com/Yoast/wordpress-seo/issues/11324
> Add KeywordForms to Snippet components

- composites/OnboardingWizard/OnboardingWizard.js
- grunt/config/eslint.js
* Add step-specific hashes to the URL in the OnboardingWizard to make navigation easier.
* N/A
* See https://github.com/Yoast/wordpress-seo/pull/12162
Fixes #[12158](https://github.com/Yoast/wordpress-seo/issues/12158)
> Add step-specific hashes to the URL in the OnboardingWizard

- package.json
- yarn.lock
* [non-user-facing] Version bump for YoastSEO (to 1.48.0)
* N/A
* See: https://github.com/Yoast/Wiki/wiki/Testing-YoastSEO.js-version-bumps-on-Yoast-Components
Fixes #
> Bump yoastseojs to 1.48
